[하디] 2,3단계 자동 DI 미션 제출합니다.
woowacourse/android-di pull request #103
Opened 2024-09-11 07:13 UTC by ii2001

에디! 
스텝 2,3도 
잘부탁드리겠습니다!

2024-09-13 17:29 UTC, junjange requested changes
하디 고생하셨어요~~ 🫡
전체적으로 코드 잘 작성해주셨고, 몇 가지 작은 부분만 수정하면 될 것 같아요!
코멘트 남긴 부분 확인해주시고, 질문 있으면 언제든지 말씀해주세요~ 😊

2024-09-13 17:29 UTC, junjange commented on app/build.gradle.kts
> +    implementation("androidx.compose.ui:ui-text-android:1.7.0")
!!!!!

2024-09-13 17:29 UTC, junjange commented on app/src/main/java/woowacourse/shopping/data/CartRepository.kt
> +
`@Qualifier` 어노테이션을 작성하지 않으면 어떤 객체를 주입하나요?!

2024-09-13 17:29 UTC, junjange commented on app/src/main/java/woowacourse/shopping/ui/MainActivity.kt
> +        DIContainer.resolve(MainViewModel::class.java, "MainViewModel")
`"MainViewModel"` 상수화해도 좋을 것 같아요

2024-09-13 17:29 UTC, junjange commented on di/src/main/java/shopping/di/Qualifier.kt
> +@Retention(AnnotationRetention.RUNTIME)
간단하게 설명해주세요!

2024-09-13 17:29 UTC, junjange commented on app/build.gradle.kts
> +    androidTestImplementation("org.mockito:mockito-android:3.9.0")
`mockito`를 사용하신 이유가 있을까요?!

2024-09-19 04:48 UTC, ii2001 commented on app/build.gradle.kts
> +    implementation("androidx.compose.ui:ui-text-android:1.7.0")
?????

2024-09-19 04:49 UTC, ii2001 commented on app/build.gradle.kts
> +    implementation("androidx.compose.ui:ui-text-android:1.7.0")
요게 왜 들어갔지..? ㅎㅎ... 파일을 착각했나봐요 지웠습니다!

2024-09-19 04:57 UTC, ii2001 commented on app/src/main/java/woowacourse/shopping/data/CartRepository.kt
> +
repository에 작성하지 않으면 null로 간주되어서 resolve함수에서 없이 등록되어있는 인스턴스를 찾게 됩니다!

2024-09-19 05:03 UTC, ii2001 commented on di/src/main/java/shopping/di/Qualifier.kt
> +@Retention(AnnotationRetention.RUNTIME)
@Target은 어노테이션이 적용 될 수 있는 대상을 지정하는거라서 필드, 함수, 파라미터에 허용하도록 해놨습니다

@Retention은 어노테이션이 런다임시에 어노테이션 정보가 유지되게 만들었습니다!

2024-09-19 05:05 UTC, ii2001 commented on app/build.gradle.kts
> +    androidTestImplementation("org.mockito:mockito-android:3.9.0")
DITest를 할때 필요해서 추가해놨습니다!

2024-09-19 06:44 UTC, merged