[호두] 2, 3단계 자동 DI 미션 제출합니다.
woowacourse/android-di pull request #110
Opened 2024-09-12 05:58 UTC by Junyoung-WON

# 만들면서 배우는 DI - 2,3단계 : Recursive DI, Qualifier, 모듈 분리

안녕하세요~ 심지! 이번 한 주도 참 정신 없었네요...! 정말 고생 많았어요!

2, 3단계 요구사항을 최대한 만족시키려 했습니다. 다만, 역시나 테스트가 까다로웠어요. 😟
특히 Activity에 관한 테스트가 동작하지 않는데, 이것 저것 시도해보다가 시간이 너무 걸렸네요.
그래서 우선 기능 구현에 집중하여 미션을 마무리 짓겠습니다!

의존성 주입과 어노테이션 활용에 관해서도 부족한게 많고, 저번에 피드백 주셨던 DSL의 활용도 아직은 공부 중에 있어요.
개선해야 할 부분이 많으니 차근차근 나아가보려합니다!

아래는 주요 구현 사항들을 간략하게 정리해보았습니다~
좋은 개선 사항이나, 피드백 줄 것이 있다면 과감하게 알려주세요!!

## 주요 구현 내용

### 재귀적으로 의존성 주입 : [4568725](https://github.com/woowacourse/android-di/commit/4568725ac3ea665935778342df84c47341d98232)
- 레퍼런스 객체(KClass)에 대해 재귀적으로 접근하여 의존성을 주입하는 로직을 구현했습니다.
  - 다만, 주 생성자에 많이 의존적인 코드인 것이 느껴져요. 단순히 주 생성자의 유무에 따라 인터페이스와 그 구현체를 구분짓고 있습니다.
  - 레퍼런스 객체의 `isAbstract` 등의 속성들을 잘 확인해서, 인터페이스 등 상속의 대상인지, 또는 생성자로 인스턴스화가 가능한 구현체인지 판단하는 로직으로 변경해보면 어떨까 합니다.

### 레포지토리 구현체 이름 변경 : [ff13c1c](https://github.com/Junyoung-WON/android-di/commit/ff13c1c97b90396dd70fb7ab5400374eb6c43884)
- 호두의 컨벤션을 떠나보내고, 우리에게 더 친숙한 컨벤션으로 적용해보았습니다 😅

### Qualifier 어노테이션 추가 및 적용 : [7b0f847](https://github.com/Junyoung-WON/android-di/commit/7b0f847aeb74044f20db1100d828209ede853875)
- 어색하게나마 `Qualifier` 어노테이션을 작성하고, 이를 활용해 구현체를 구분지을 수 있도록 구현해보았습니다.
- 이 `Qualifier`는 테스트를 작성할 때 활용해보았어요.
  - 구현은 상대적으로 간단했지만, 개발자 입장에서 그리 편리한 방식은 아닌 것 같네요... 🥲
  - 완전히 자동적인 의존성 주입과도 거리가 조금 있어보였습니다. 개선해보아야 할 부분입니다!
- 어노테이션을 더욱 적극적으로 활용한다면, 개선할 수 있을 것 같아요. Hilt는 어떻게 동작하는지 더 공부를 해보아야겠네요.

### 의존성 주입 테스트 수정 : [93de6e0](https://github.com/woowacourse/android-di/commit/93de6e07ba99ab6879b8eff814cb6a9c248ed340)
- 모듈을 분리하는 과정에서, 기존의 의존성 주입에 관한 테스트를 수정해보았습니다.
  - 현재 레포지토리와 비슷한 구조의 가짜 클래스들을 만들어서 테스트 코드를 작성해보았어요.
  - `Qualifier` 도 함께 추가하여 테스트를 진행해보았는데, 분리가 필요하다고 생각합니다.
- 더 다양한 의존성 주입에 관한 테스트를 작성할 수 있겠네요. 점차 늘려나가볼게요!

## 고민 거리
- DSL은 어디서 적용시킬 수 있을까?
  - 강의자료를 다시 살펴보자.
- Hilt 처럼 어노테이션을 활용할 수 있도록 구현하려면 어떻게 해야할까?
  - Hilt 의 내부 동작방식을 잘 살펴보자.
- 지금 구현된 의존성 주입 코드의 문제점은?
  - 주 생성자의 파라미터 중 의존성 주입을 받지 않는 것이 있는 경우, 얘는 사용할 수 없다. (터진다)
  - 주 생성자가 null 인지 확인하는 로직이 어색하다.
  - class? object? fun? 뭘로 두어야할까? 무엇으로 두어야 테스트도 용이할까?
  - DependencyContainer 를 지금 구현과 같이 받아도 될까?
    ```kotlin
    lateinit var dependencyContainer
    fun setContainer(newContainer: DependencyContainer) {
        dependencyContainer = newContainer
    }
    ```
- DependencyContainer를 인터페이스로 두었지만, 어떻게 더 활용할 수 있을까?
- 여기서 뷰의 라이프사이클까지 신경쓴다고...?

2024-09-14 05:49 UTC, sh1mj1 approved these changes
고생 많으셨습니다!!!!!
테스트도 많이 구현이 되어있어, 비교적 이해하는데 수월했습니다!!
생각해볼 점 코멘트로 달아 두었습니다.
여유 있을 때 답변 부탁드려요!  저도 아직 익숙치 않아서 이야기 많이 나눠 보면 좋을 것 가탕요

현재 미션의 요구사항에서는 이 정도로 충분해 보여서, 바로 level4 를 진행하시면서 개선할 점 개선해도 좋을 것 같아요.
물론, 개선할 점부터 수정 후에 다시 2,3 단계 PR 을 다시 요청하셔도 됩니다!

2024-09-14 05:49 UTC, sh1mj1 commented on di/src/main/java/woowacourse/shopping/di/DependencyInjector.kt
> +        if (primaryConstructor == null) {
이 코드가 주생성자가 없는, 즉, 인터페이스일 때 분기해주는 코드일까요?

2024-09-14 05:49 UTC, sh1mj1 commented on di/src/main/java/woowacourse/shopping/di/DependencyInjector.kt
> +        if (primaryConstructor == null) {
만약 주 생성자가 없지만 인터페이스가 아닌 경우는 어떻게 될까요?
예를 들면 아래처럼 만들어진다면???

```kotlin
class ShoppingApplication : Application() {
    // ....

    override fun onCreate() {
        super.onCreate()
        // ....
        defaultDependencyContainer.setDependency(
            CartRepository::class,
            ObjectCartRepo::class,
            "",
        // ....
        DependencyInjector.initDependencyContainer(defaultDependencyContainer)
    }

    companion object {
        val defaultDependencyContainer: DependencyContainer by lazy {
            DefaultDependencyContainer()
        }
    }
}

```

```kotlin
object ObjectCartRepo: CartRepository {
    private val cartProducts = mutableListOf<CartProduct>()

    override suspend fun addCartProduct(product: Product) {
        cartProducts.add(
            CartProduct(
                id = 0,
                name = product.name,
                price = product.price,
                imageUrl = product.imageUrl,
                addedAt = 0L,
            ),
        )
    }

    override suspend fun getAllCartProducts(): List<CartProduct> {
        return cartProducts.toList()
    }

    override suspend fun deleteCartProduct(id: Long) {
        cartProducts.first { id == it.id }
    }
}
```

2024-09-14 05:49 UTC, sh1mj1 commented on di/src/main/java/woowacourse/shopping/di/DependencyInjector.kt
> +            createInstanceFromConstructor(classifier.java)
이런 식으로 재귀 DI 를 해줄 수 있군요! 👍👍👍👍👍👍👍👍👍👍👍

2024-09-14 05:49 UTC, sh1mj1 commented on app/src/test/java/woowacourse/shopping/study/AnnotationReflectionTest.kt
> +import kotlin.reflect.full.hasAnnotation
`kotlin.reflect.full.hasAnnotation`  가 Unresolved reference: full 이군요.

`app/build.gradle.kts` 에서 reflect 에 대한 의존성을 제거했는데 
이 학습 테스트 코드가 app 모듈 안에 있어서 그런 것 같아요.

2024-09-14 05:49 UTC, sh1mj1 commented on app/src/test/java/woowacourse/shopping/ui/MainViewModelTest.kt
>      }
이렇게 테스트를 해주셨군요!
저는 뷰모델을 테스트할 때 DependencyInjector 와의 연관성을 가지지 않도록 하고 싶었어요.
그런데 주 생성자 파라미터가 아닌 멤버 프로퍼티를 set 해주기가 어렵더라구요.
(그래서 제 코드에서는 그 프로퍼티가 private 이 아닙니다.. ㅠㅜ)

호두는 뷰모델을 테스트할 때 `DependencyInjector` 라는 외부 DI 라이브러리와 의존성이 있어도 괜찮다고 생각하시나요?

2024-09-14 05:49 UTC, sh1mj1 commented on di/src/test/java/woowacourse/shopping/di/DependencyAutoInjectTest.kt
오 피드백 수업 이전에 이미 Fake Stub 을 사용해서 테스트를 수행했었군요!!!! 대단해요!~

2024-09-14 05:49 UTC, sh1mj1 commented on di/src/test/java/woowacourse/shopping/di/DependencyAutoInjectTest.kt
> +        fakeDependencyContainer = FakeDependencyContainer()
이 부분에서 굳이 fake 객체를 가지고 테스트할 필요가 있나요?
`DefaultDependencyContainer` 를 사용하는 것과 동일하다면, Default 객체를 가지고 테스트 하는 것이 테스트 신뢰성을 더 높일 수 있지 않을까 싶어서요

2024-09-14 05:49 UTC, sh1mj1 commented on di/src/test/java/woowacourse/shopping/di/DependencyAutoInjectTest.kt
> +        fakeDependencyContainer = FakeDependencyContainer()
만약 fake 객체를 꼭 써야 겠다면, `알맞은 인스턴스를 주입한다` 테스트에서 `fakeDependencyContainer.setDependency` 라는 것에 대한 의존이 없도록 하기 위해
`dependencies: MutableMap<Pair<KClassifier, String>, KClass<*>>` 를 생성자 주입을 통해 설정해주는 것으로 하는 게 fake 객체 사용의 의도에 맞아 보여요.

다른 이유가 있는지 호두 생각이 궁금해요!

2024-09-14 05:49 UTC, sh1mj1 commented on di/src/main/java/woowacourse/shopping/di/DependencyInjectAnnotation.kt
> +annotation class ParamInject
`@ParamInject` 는 현재 쓰이는 곳이 없어 보이는데 이 애노테이션의 의도가 궁금해요!

2024-09-14 05:49 UTC, sh1mj1 commented on app/src/test/java/woowacourse/shopping/FakeRepositoryObjects.kt
> +class FakeRepositoryImpl : FakeRepository
이것도 다른 곳에서 안 쓰이는 것 같아요

2024-09-14 05:49 UTC, sh1mj1 commented on di/src/main/java/woowacourse/shopping/di/DefaultDependencyContainer.kt
> +class DefaultDependencyContainer : DependencyContainer {
default 라는 네이밍이 조금 어색한 것 같기도 하네요..?
 level4 에서는 `DependencyContainer` 를 상속받는 다른 컨테이너 구현체도 생길 것 같은데 
그 때 필요하면 바꾸는 방향으로 해도 될것 같아요~

2024-09-14 05:49 UTC, sh1mj1 commented on di/src/main/java/woowacourse/shopping/di/DependencyInjector.kt
API 의 네이밍들이 바로 이해되지는 않았어요 (제 역량 문제일 수도 있음)
미션 진행하면서 천천히 고민해보면 좋을 것 같아요

2024-09-14 05:54 UTC, sh1mj1 commented
### 재귀적으로 의존성 주입 : [4568725](https://github.com/woowacourse/android-di/commit/4568725ac3ea665935778342df84c47341d98232)
[관련 코멘트입니다.](https://github.com/woowacourse/android-di/pull/110#discussion_r1759669781)
---
### 레포지토리 구현체 이름 변경 : [ff13c1c](https://github.com/Junyoung-WON/android-di/commit/ff13c1c97b90396dd70fb7ab5400374eb6c43884)
편안하네요 ㅋㅋㅋㅋ
---

### Qualifier 어노테이션 추가 및 적용 : [7b0f847](https://github.com/Junyoung-WON/android-di/commit/7b0f847aeb74044f20db1100d828209ede853875)

저도 이 부분에 대해 고민이 많았었는데 결론적으로 호두와 비슷한 방법으로 구현한 것 같습니다.
hilt 에서는 kapt 나 ksp 가 `~~Repository_hilt_factory` 등등의 이름으로 팩토리 클래스와 구현체 클래스를 만들어준다고 알고 있어요.
그래서 힐트의 방식을 완전히 적용하기는 힘들 것이라는 점만 알고 계시면 될 것 같아요~
---

#### DSL은 어디서 적용시킬 수 있을까?

2024-09-14 06:01 UTC, sh1mj1 requested changes
고생 많으셨습니다!!!!!
테스트도 많이 구현이 되어있어, 비교적 이해하는데 수월했습니다!!
생각해볼 점 코멘트로 달아 두었습니다.
여유 있을 때 답변 부탁드려요! 저도 아직 익숙치 않아서 이야기 많이 나눠 보면 좋을 것 가탕요

현재 미션의 요구사항에서는 이 정도로 충분해 보여서, 바로 level4 를 진행하시면서 개선할 점 개선해도 좋을 것 같아요.
approve 원하시면 바로 해드릴게요~
물론, 개선할 점부터 수정 후에 다시 2,3 단계 PR 을 다시 요청하셔도 됩니다!

2024-09-21 05:02 UTC, Junyoung-WON commented on di/src/main/java/woowacourse/shopping/di/DependencyInjector.kt
> +        if (primaryConstructor == null) {
그렇네요...! object 는 생성자가 제공되지 않는군요!
그래서 constructor에 접근할 수 없기 때문에, 제가 작성한 코드는 object에 대한 의존성 주입을 할 수 없습니다.

`KClass`의 주생성자가 null인 경우, `objectInstance` 가 존재하는지 확인해서 해당 싱글톤 인스턴스에 의존성 주입을 수행하도록 코드를 변경했습니다.

```kotlin
    // ...
        val targetInstance: T = checkClassTypeThenGetInstance(modelClass, qualifier)
        setDependencyOfProperties(modelClass, targetInstance)
    // ...

    private fun <T : Any> checkClassTypeThenGetInstance(
        modelClass: KClass<T>,
        qualifier: AnnotationQualifier,
    ): T {
        val objectInstance: T? = modelClass.objectInstance
        val primaryConstructor: KFunction<T>? = modelClass.primaryConstructor
        return if (primaryConstructor == null) {
            getInstanceFromDependencyContainer(modelClass, qualifier)
        } else if (objectInstance != null) {
            objectInstance
        } else {
            primaryConstructor.isAccessible = true
            getInstanceFromConstructor(primaryConstructor)
        }
    }
```

2024-09-21 05:04 UTC, Junyoung-WON commented on app/src/test/java/woowacourse/shopping/study/AnnotationReflectionTest.kt
> +import kotlin.reflect.full.hasAnnotation
학습 테스트는 모듈 분리를 할 때 같이 옮기는걸 까먹었네요...ㅎㅎ 😅
학습 테스트 코트도 di 모듈로 함께 옮겼습니다!

2024-09-21 05:18 UTC, Junyoung-WON commented on app/src/test/java/woowacourse/shopping/ui/MainViewModelTest.kt
>      }
저는 처음에는 테스트 코드에 함께 있어도 괜찮겠다는 생각이었지만, 모듈을 분리하고 나서 심지의 의견에 동의하게 되었어요!
외부 라이브러리에 대한 테스트는 분리한 모듈에서 따로 행할 수 있기 때문에, `ViewModel` 테스트에서 `DependencyInjector`에 대한 연관성이 있다면 테스트가 복잡해질 것 같아요.
그래서 저도 테스트를 분리하는 과정에서, `ViewModel`의 멤버 프로퍼티를 set 해주기 위해 접근 제한을 `public`으로 두었습니다.
private이 아닌게 너무 이상하지만, 테스트의 역할 분리가 잘 이루어져서, 괜찮은 선택을 했다고 생각합니다..!

2024-09-21 05:19 UTC, Junyoung-WON commented on app/src/test/java/woowacourse/shopping/ui/MainViewModelTest.kt
>      }
통합 테스트의 관점에서는 뷰모델과 `DependencyInjector`를 함께 사용하는 것도 괜찮은 것 같네요...!

2024-09-21 05:23 UTC, Junyoung-WON commented on di/src/test/java/woowacourse/shopping/di/DependencyAutoInjectTest.kt
> +        fakeDependencyContainer = FakeDependencyContainer()
확실히 구현 자체도 비슷한 Fake 객체를 사용하기보다는 `DefaultDependencyContainer`로 테스트를 진행하는게 좋겠네요!
테스트의 신뢰성을 높일 수 있다는 심지 의견에 동의합니다!

처음 의도는 DependencyContainer 인터페이스를 상속받는 Fake 객체를 생성해서 테스트를 원활히 진행하고자 했는데, 기존 구현체와 내부 구현이 비슷해서 Fake 객체를 활용하는 의미가 사라진 것 같네요.

2024-09-21 05:25 UTC, Junyoung-WON commented on di/src/main/java/woowacourse/shopping/di/DependencyInjectAnnotation.kt
> +annotation class ParamInject
주 생성자의 파라미터에 들어가는 인스턴스 중, 의존성 주입이 필요한 객체를 구분하기 위해 만들어두었습니다!
하지만 미션 요구사항이 변경되면서 지금은 사용하지 않고 있네요.
이렇게 의존성 주입을 구분지을 수 있다면 편리하지 않을까, 더 개선할 방법은 없을까 하는 생각에 제거하지 않았습니다!

2024-09-21 05:26 UTC, Junyoung-WON commented on app/src/test/java/woowacourse/shopping/FakeRepositoryObjects.kt
> +class FakeRepositoryImpl : FakeRepository
임시로 만들어두었다가 결국 사용하지 않는 객체들이네요~
제거 완료했습니다!

2024-09-21 05:27 UTC, Junyoung-WON commented on di/src/main/java/woowacourse/shopping/di/DependencyInjector.kt
나름 의미를 부여한다고는 했는데, 구현이 바뀌면서 메서드의 의미도 모호해진 것들이 있네요.
리팩터링 진행하면서 메서드 이름을 좀 더 구체적으로 수정해보았습니다!

2024-09-21 05:38 UTC, Junyoung-WON commented
안녕하세요, 심지! 추석은 잘 보내셨나요!
어노테이션에 대한 테스트를 추가로 작성하는 중에 Qualifier 어노테이션에 대한 동작이 제대로 이루어지지 않은 것을 뒤늦게 확인했습니다.
에러를 잡느라 어제 중으로 보내려고 했던 PR이 늦어졌네요... 😭

심지와 더 많은 이야기를 나누지 못한 것 같아 아쉽네요. 다음 미션은 빠르게 구현을 마치고, 남은 시간에는 좀 더 활발하게 이야기를 나누어보고 싶습니다!

- [코드 변경점 비교](https://github.com/Junyoung-WON/android-di/compare/6778d197686d26caef19924f03358b2605ec3a29..6af62469595da017c072c462eab02899d583e1f1)

아래는 주요 리팩터링 사항입니다!

- object 에 대한 의존성 주입 가능하도록 변경 : [9004af1](https://github.com/woowacourse/android-di/pull/110/commits/9004af1c49cd55ab8c5e7a2afe02ac7aec061b86)
- 뷰모델 테스트 분리 : [97012b0](https://github.com/woowacourse/android-di/pull/110/commits/97012b092db6cd695d673398ca370bf663ee5e6c)
- Qualifier 어노테이션 오류 수정 : [ca667ef](https://github.com/woowacourse/android-di/pull/110/commits/ca667ef86c6ef029aea6a892bdd9165938f24e93)
- Qualifier 어노테이션의 활용 방안 변경 : [6af6246](https://github.com/woowacourse/android-di/pull/110/commits/6af62469595da017c072c462eab02899d583e1f1)

2024-09-22 01:59 UTC, sh1mj1 approved these changes
고생 많으셨습니다!!!
다음 미션 제출까지도 시간이 얼마 남지 않았군요..
화이팅 해봅시다!!!!

참고로 4단계 미션에서는
 PR 본문에 아래 내용을 첨부하는 것도 잊지 마세용~
> 내가 만든 것은 라이브러리인가? 프레임워크인가?
내가 만든 것은 서비스 로케이터인가? DI인가?
내가 만든 것은 자동 DI인가? 수동 DI인가?
안드로이드 애플리케이션의 구조적 한계
그런데 사용자에게 맡기는 게 자연스러운 걸까?

2024-09-22 01:59 UTC, sh1mj1 commented on app/src/test/java/woowacourse/shopping/ui/MainViewModelTest.kt
>      }
👍👍👍👍 다른 크루들은 이런 문제에 대해 어떻게 대처했는지 궁금하기도 하네요.
나중에 이것에 대해 같이 이야기 해보면 좋을 것 같아요~

2024-09-22 01:59 UTC, merged