[악어] 2,3 단계 자동 DI 미션 제출합니다
woowacourse/android-di pull request #114
Opened 2024-09-12 08:14 UTC by Hogu59

알송 안녕하세요,
이번 과제에 대한 내용에 대한 이해도가 높지 않아 아마 코드에 난독화가 적용되었나 싶을 것 같습니다...
계속 수정해보도록 하겠습니다. 굵직한 부분부터 리뷰주시면 계속 수정해보겠습니다!

감사합니다!

2024-09-13 05:41 UTC, songpink commented on app/src/main/java/woowacourse/shopping/ShoppingApplication.kt
> +        setInstance(CartRepository::class, InMemoryCartRepository(), "inMemory")
```
setInstance(CartRepository::class, DefaultCartRepository(cartProductDao), "room")
```
이 코드를 자동 주입이라고 볼 수 있는지 궁금합니다!

2024-09-14 11:33 UTC, songpink requested changes
수고 많으셨습니다 악어! 👍 악어는 코드가 더럽다고 하셨지만 저는 전반적으로 가독성이 좋았다고 생각합니다! ㅎㅎ 버그가 몇가지 있지만 수정하시고, 뷰모델의 생명주기 관련해서 같이 얘기해 보고 싶네요! 테스트도 보완 후 다시 리뷰요청 주세요~~ 🐊

2024-09-14 11:33 UTC, songpink commented on app/src/main/java/woowacourse/shopping/ShoppingApplication.kt
> +        DIContainer.setViewModelInstance(CartViewModel::class, CartViewModel())
저도 악어의 버그가 어느 부분에서 문제가 발생하는지는 파악했는데요, 이 부분이 왜 문제인지는 아직 정확히 모르겠는 상태입니다..

악어도 버그 수정 해보시고, 어떤 원인으로 버그가 발생했는지 공유해 주시면 고맙겠어요!!

2024-09-19 03:42 UTC, Hogu59 commented on app/src/main/java/woowacourse/shopping/data/DefaultCartRepository.kt
>  // TODO: Step2 - CartProductDao를 참조하도록 변경
삭제했습니다!

2024-09-19 03:44 UTC, Hogu59 commented on README.md
> +- [ ] 내가 만든 DI 라이브러리를 배포하고 적용한다.
🚀 수정했습니다!

2024-09-20 00:12 UTC, Hogu59 commented on app/src/main/java/woowacourse/shopping/ui/cart/CartViewModel.kt
>      }
수-정-완-료 입니다! 😄

2024-09-20 00:14 UTC, Hogu59 commented on di/src/main/java/com/example/di/annotations/Qualifier.kt
> +)
enum class 로 따로 관리하면 더 좋을것 같네요!
관리할 value가 많아지면 (저에게는 5개 정도가 많다의 기준인 것 같습니다) 만들도록 하겠습니다!

2024-09-20 06:14 UTC, Hogu59 commented on app/src/main/java/woowacourse/shopping/ShoppingApplication.kt
> +        setInstance(CartRepository::class, DefaultCartRepository(cartProductDao), "room")
그러게요... 많은 고민을 해봤는데 참 쉽지 않은 지점인 것 같습니다...
어떻게 하면 좋을까 고민을 해봤는데, 결론은 이렇게 해주는게 차선책이지 않을까 싶긴합니다.

dao를 넘겨주지 않겠다고 한다면, 엄밀하게는 dao객체를 미리 만드는 행위를 하지 않는다고 할 때,
결국엔 어딘가에서 만들때는 Context를 필요로 하게 됩니다.

그러면 결국 여기서 dao를 넣어주지 않는다고 해도 database 혹은 database를 만들기 위한 context를 넘겨줘서 Container 에서 결국엔 dao 객체를 만들어야할 것 같은데, 과연 유의미한 변화일까에 대한 생각이 드네요....

2024-09-20 06:17 UTC, Hogu59 commented on app/src/main/java/woowacourse/shopping/ShoppingApplication.kt
> +        setInstance(CartRepository::class, DefaultCartRepository(cartProductDao), "room")
흠... 생각해보면 context를 넘겨줘서 다양한 db에 접근 할 수 있도록 할 수 있다는 점에서 유의미할 것 같군요...
dao가 여러개이더라도 대응할 수 있도록 확장성을 열었다고 생각할 수도 있을것 같네요.

혹시 rc를 하신다면 수정하면서 같이, 머지된다면 다음 미션 진행하면서 변경해보고 어떤게 나았는지 적어보겠습니다!

2024-09-20 06:34 UTC, Hogu59 commented on app/src/main/java/woowacourse/shopping/ui/MainViewModel.kt
> +
```kotlin
@Target(AnnotationTarget.FIELD, AnnotationTarget.CONSTRUCTOR)
@Retention(AnnotationRetention.RUNTIME)
annotation class Qualifier(
    val value: String,
)
```

이런 식으로 확장성을 열어둔다면 가능할 것 같다고 생각했습니다!

2024-09-20 06:49 UTC, Hogu59 commented on app/src/main/java/woowacourse/shopping/di/DefaultAppModule.kt
> +    override val cartRepository: CartRepository by lazy { inject<CartRepository>() }
[위에서 얘기했던](https://github.com/woowacourse/android-di/pull/114#discussion_r1768045109) 내용의 변형으로 module을 Container에 담으면 유효할 것 같군요!
현재로서는 사용성이 없는 코드라서 삭제처리하도록 하겠습니다!

2024-09-20 10:37 UTC, Hogu59 commented on app/src/main/java/woowacourse/shopping/ShoppingApplication.kt
> +        DIContainer.setViewModelInstance(CartViewModel::class, CartViewModel())
오프라인으로 어제 얘기했던 것처럼 인스턴스를 미리 만든 지점에서 문제가 생긴 것 같습니다.
해당 내용 인스턴스를 생성하도록 변경하여 버그 고쳐두었습니다!

알려주셔서 감사합니다! 🙇

2024-09-21 05:15 UTC, songpink commented on app/src/main/java/woowacourse/shopping/ui/MainViewModel.kt
> +
그것에 대한 피드백은 아니었고, 사실 init블럭에 대한 코멘트였어요.

물론 동작은 문제 없겠지만 이 라이브러리를 사용하는 개발자의 입장에서 필드 주입을 하기 위해서는 반드시 클래스에 init 블럭을 열어야 한다는 것이 불편하게 여겨질 거라고 생각했어요. 

게다가 init블럭으로는 생성자 주입은 해줄 수가 없죠..! 따라서 init블럭을 사용하지 않고 구현한다고 했을 때, 생성자 주입도 같이 가능하게 해 보면 어떻겠냐는 의견이었습니다! ㅎㅎ

물론 4단계 미션이 마감 기한이 얼마 남지 않았고 요구사항에도 생성자 주입은 없기 때문에 지금은 4단계 미션에 집중하시는 것이 좋다고 생각합니다!

2024-09-21 05:49 UTC, songpink commented on app/src/main/java/woowacourse/shopping/ShoppingApplication.kt
> +        setInstance(CartRepository::class, DefaultCartRepository(cartProductDao), "room")
제 생각을 말씀드려보고 싶은데요, 
> dao를 넘겨주지 않겠다고 한다면, 엄밀하게는 dao객체를 미리 만드는 행위를 하지 않는다고 할 때,

반드시 dao객체를 미리 만드는 행위를 하지 않아야 할까요? 자동 DI의 동작 원리를 생각해 보세요. 
현재 악어가 구현한 자동 DI는 먼저 특정 타입에 해당하는 의존성을 `DIContatiner.instances` 에 등록해 두고 주입할 때에는 주입할 필드의 타입에 해당하는 의존성을 `DIContatiner.instances`에서 꺼내서 주입합니다.

그렇다면 dao객체도 마찬가지의 방법으로 주입하면 되는 것이 아닐까요?

그리고 악어의 코드도 이미 이렇게 하고 있습니다. ShoppingApplication에서 아래 작업을 해주고 있죠!
```
val cartProductDao = appModule.database.cartProductDao()
setInstance(CartProductDao::class, cartProductDao)
```
그런데 현재 문제는 이렇게 만든 dao 인스턴스를 수동으로 주입하고 있다는 점입니다. 자동으로는 주입해주지 못하고 있어요.

왜냐하면 악어가 생성자 주입 기능을 구현하지 않았는데 DefaultCartRepository는 생성자로 dao를 받아야 하거든요.

```
class DefaultCartRepository(
    private val cartProductDao: CartProductDao,
) : CartRepository {
    override suspend fun addCartProduct(product: Product) {
        cartProductDao.insert(product.toEntity())
    }

    override suspend fun getAllCartProducts(): List<Product> = cartProductDao.getAll().map { it.toModel() }

    override suspend fun deleteCartProduct(id: Int) {
        cartProductDao.delete(id)
    }
}
```

그러면 그냥 이 객체도 필드로 dao를 주입받으면 해결되는거죠 ㅎㅎ

제가 드린 피드백의 의도와 맞지 않게 방향을 아예 잘못 잡고 계신 것 같아서 조금 구체적으로 의견 남깁니다 😁

2024-09-21 06:46 UTC, songpink commented on app/src/main/java/woowacourse/shopping/ShoppingApplication.kt
> +        setInstance(CartRepository::class, DefaultCartRepository(cartProductDao), "room")
새로 리뷰요청하신 커밋에는 createInstance라는 함수를 새로 만드셨네요! 이 함수를 쓴다면 recursive 주입을 통해서도 dao를 자동주입 할 수 있을 것 같습니다. 하지만 지금은 4단계 미션에 집중 부탁드릴게요 😅

2024-09-21 07:17 UTC, songpink approved these changes
수고하셨습니다 악어~ 🐊 이번 2,3단계 미션을 진행하면서 DI뿐만 아니라 뷰모델의 생명주기에 대해서 같이 논의하고 많이 얻어간 것 같아서 보람차네요 ㅎㅎ

제 피드백을 반영하시면서 리팩토링과 수정할 부분이 더 많이 생긴 것 같지만.. 4단계 미션을 위해 일단 머지하겠습니다. 먼저 4단계에 집중해 주시고, 새로 드린 피드백들은 4단계 이후에 반영하시면 좋을 것 같아요!

2024-09-21 07:17 UTC, songpink commented on app/src/main/java/woowacourse/shopping/ui/cart/CartViewModel.kt
> +            println("CartViewModel.deleteCartProduct id : $id")
Lod.d()함수를 쓰면 TAG를 통해 원하는 로그를 검색할 수 있어서 더 좋을텐데, println함수를 쓰시는 이유가 있을까요? 😅

그리고 로그는 지워주시면 좋겠습니다! 위의 `println()`도 마찬가지구요.

2024-09-21 07:17 UTC, songpink commented on app/src/main/java/woowacourse/shopping/ui/cart/CartViewModel.kt
> +            job.await()
코루틴에 대해 학습하시던 흔적이겠죠..? ㅋㅋㅋ 수정 부탁드립니다

2024-09-21 07:17 UTC, songpink commented on app/src/test/java/woowacourse/shopping/di/DIContainerTest.kt
> +class DIContainerTest {
DIContainerTest는 앱 모듈이 아니라 라이브러리 모듈에 있어야 하겠네요!

2024-09-21 07:17 UTC, songpink commented on app/src/main/java/woowacourse/shopping/ShoppingApplication.kt
> +        DIContainer.setViewModelInstance(CartViewModel::class, CartViewModel())
삭제.. 하셔야겠죠? ㅎㅎ

2024-09-21 07:24 UTC, merged