[차람] 4단계 자동 DI 미션 제출합니다
woowacourse/android-di pull request #132
Opened 2024-09-23 08:51 UTC by aprilgom

안녕하세요 악어
이번에도 리뷰 잘 부탁드립니다

2024-09-23 15:54 UTC, Hogu59 requested changes
차람 안녕하세요!

기존의 코드를 잘 활용해서인지 FileChange가 적었네요! 👍 
아마도 이전 미션을 진행하면서 지금의 미션을 어느정도 예상하고 설계를 진행해주셨던 것 같아요.

몇가지 질문을 남겼는데 답변 주시면 감사하겠습니다! 😄

2024-09-23 15:54 UTC, Hogu59 commented on androiddi/src/main/java/org/aprilgom/androiddi/DIContainer.kt
> +    val providers: MutableMap<NamedKClass, Provider<*>>,
MutableMap으로 바꾸셨군요! 👍

2024-09-23 15:54 UTC, Hogu59 commented on androiddi/src/main/java/org/aprilgom/androiddi/Extensions.kt
> +inline fun <reified VM : ViewModel> ComponentActivity.viewModel(): Lazy<VM> =
궁금) ComponentActivity로 변경하신 이유는 Fragment에도 대응하고 싶었기 때문일까요? 🤔

2024-09-23 15:54 UTC, Hogu59 commented on app/src/main/java/woowacourse/shopping/ShoppingApplication.kt
> +                }
다른곳에서도 동일하지만 named의 파라미터로 문자열을 받는데, 오타의 발생 가능성이 있지 않을까 싶습니다.
실수로 한글자를 틀려서 필요한 인스턴스를 못 받아오는 상황도 존재할 수 있을 것 같습니다.
이런 상황을 수정하려면 enum class나 sealed class를 사용하는 방법이 있을 것 같고, 아니면 어노테이션 클래스를 활용하는 방법도 있을 것 같습니다.

다만, 현재로서는 관리하는 대상이 늘어난다면, 나중에 실수로 인해 오류가 생길 가능성이 높아질 것 같습니다.
(해당 내용은 제생각엔 런타임에서 일어날 가능성이 더 높을 것 같아보입니다.)
이런 방식이 틀렸다는 말보다는, 차람은 어떻게 생각하시는 의견이 궁금합니다! 🤔 🤓

2024-09-23 15:54 UTC, Hogu59 commented on app/src/main/java/woowacourse/shopping/ui/cart/CartActivity.kt
> +        dateFormatter = scope.get("DateFormatter")
dateFormatter를 lazy하게 만들면 코드를 줄일 수 있을 것 같은데, 차람은 어떤 방식을 선호하시나요?
이유도 궁금합니다. 🤔

2024-09-23 15:54 UTC, Hogu59 commented on androiddi/src/test/java/org/aprilgom/androiddi/DiTest.kt
> +    }
assert 구문이 없는것 같은데 아직 작성중인 테스트인것 맞죠...?

2024-09-23 15:54 UTC, Hogu59 commented on androiddi/src/test/java/org/aprilgom/androiddi/DiTest.kt
> +        assertNotNull(repository)
notNull이라면 repository가 DefaultFakeRepository라는 것을 보장할 수 있다고 할 수 있을까요?
테스트코드가 하나의 문서라고 한다면, 마지막 assert 구문에서 신뢰성을 조금 더 실어주면 좋을 것 같아요!

2024-09-23 15:54 UTC, Hogu59 commented on androiddi/src/main/java/org/aprilgom/androiddi/ScopedProvider.kt
> +    }
drop을 통해 할당되었던 인스턴스를 null로 설정해주는군요! 👍

2024-09-23 21:49 UTC, aprilgom commented on androiddi/src/test/java/org/aprilgom/androiddi/DiTest.kt
> +    }
Junit4라서 예외를 assert가 아닌 어노테이션으로 잡을수밖에 없는거같아요

2024-09-23 22:01 UTC, aprilgom commented on app/src/main/java/woowacourse/shopping/ShoppingApplication.kt
> +                }
저도 헷갈려서 3번쯤 컴파일 실패한게 레전드입니다

2024-09-23 22:07 UTC, aprilgom commented on androiddi/src/main/java/org/aprilgom/androiddi/Extensions.kt
> +inline fun <reified VM : ViewModel> ComponentActivity.viewModel(): Lazy<VM> =
robolectric에서 appcompat을 쓰면 apptheme을 추가해달라고 난리를 펴서 그만 바꿔버렸네요

2024-09-23 22:09 UTC, aprilgom commented on androiddi/src/main/java/org/aprilgom/androiddi/DIContainer.kt
> +    val providers: MutableMap<NamedKClass, Provider<*>>,
개인적으로는 그러고싶지 않았지만, 런타임에서 context추가는 해야하고 시간은 없고.. 그래서 그냥 풀어버렸습니다.

2024-09-26 08:58 UTC, Hogu59 approved these changes
차람 안녕하세요!

답글 달아주시느라 수고 많았습니다. 미션과 프로젝트 둘 다 병행하는게 쉽지 않은것 같아요!
차람의 코드는 잘 다듬어져 있어서 크게 더 수정할 내용이 없어 이만 어프루브 & 머지 하도록 하겠습니다.

수고 많으셨고, 이후 복잡한 뷰 챌린지와 프로젝트도 파이팅입니다! 💪

2024-09-26 08:58 UTC, merged