[해나] 4단계 자동 DI 미션 제출합니다
woowacourse/android-di pull request #142
Opened 2024-09-23 08:57 UTC by hxeyexn

## 1. 내가 만든 것은 라이브러리인가? 프레임워크인가?
제가 만든 것은 라이브러리에 가깝습니다. 
`annotation`을 이용해 자동 DI에 필요한 메서드를 호출하는 형식으로 주도권이 사용자에게 있습니다. 
또한 애플리케이션의 구조나 흐름을 결정하지 않고, 단지 의존성을 관리하는 도구로 사용됩니다. 
따라서 제어권을 주도하는 프레임워크와는 거리가 멀다고 생각합니다.

## 2. 내가 만든 것은 서비스 로케이터인가? DI인가?
제가 만든 것은 서비스 로케이터와 의존성 주입(DI) 두 가지 패턴이 혼합된 형태이며, 서비스 로케이터의 성향이 좀 더 강하다고 생각합니다.

ViewModel 생성 시에는 `GlobalViewModelFactory`가 필요한 의존성을 직접 요청하고 획득하는 방식으로, 이는 `서비스 로케이터`에 가깝습니다. 즉, 객체가 자신의 의존성을 직접 찾아 사용하는 구조입니다. 또한 리플렉션을 사용해 구현했기 때문에 클래스의 의존성을 숨겨서 컴파일 타임 오류가 아닌 런타임 오류를 발생시키므로 서비스 로케이터의 성향을 가지고 있습니다.

반면 Repository 주입 시에는 외부에서 필요한 의존성을 주입해주는 방식을 따르므로, 이는 `DI`에 가깝습니다. 객체는 의존성을 직접 요청하지 않고, 외부에서 필요한 의존성을 주입받아 사용하는 구조입니다.

## 3. 내가 만든 것은 자동 DI인가? 수동 DI인가?
제가 만든 것은 자동 DI와 수동 DI가 혼합된 형태입니다.

 - ### 안드로이드 애플리케이션의 구조적 한계
 안드로이드 애플리케이션은 다양한 컴포넌트의 생명주기에 맞춰 객체를 관리해야 하므로 구조적 한계가 있는 것 같습니다.. 이로 인해 완전한 자동 DI를 적용하기 어렵거나, 제한된 상황에서만 적용할 수 있습니다.

 - ### 그런데 사용자에게 맡기는 게 자연스러운 걸까?

2024-09-24 01:06 UTC, woowahan-leah commented on app/src/main/java/woowacourse/shopping/ui/product/MainViewModel.kt
> +    }
이 어플리케이션에 존재하는 모든 ViewModel은 요 clear 구문을 호출해야 하는걸까요? 🤔

2024-09-25 01:46 UTC, haeum808 requested changes
고생하셨습니다 해나!

상품을 담고 장바구니에서 삭제한뒤 다시 앱을 실행하고 상품을 담고 장바구니로 가면 아래와 같은 예외가 나오네요.
그리고 상품을 여러 개 넣고 삭제해도 예외가 발생합니다! 해결 부탁드립니다!


`java.lang.RuntimeException: Unable to start activity ComponentInfo{woowacourse.shopping/woowacourse.shopping.ui.cart.CartActivity}: java.lang.IllegalArgumentException: 적합한 생성자를 찾을 수 없습니다.`

2024-09-25 01:46 UTC, haeum808 commented on app/src/main/java/woowacourse/shopping/GlobalViewModelFactory.kt
>  class GlobalViewModelFactory : ViewModelProvider.Factory {
ViewModelFactory가 해나가 만든 모듈에 있어야 사용하기 편리할거 같아요

2024-09-25 01:46 UTC, haeum808 commented on app/src/main/java/woowacourse/shopping/LifecycleTracker.kt
> +class LifecycleTracker : DefaultLifecycleObserver {
👍

2024-09-25 01:46 UTC, haeum808 commented on di/src/main/java/com/woowacourse/di/DependencyInjector.kt
> +class DependencyInjector {
전체적으로 함수명도 좋고 분리도 잘 되어 있어서 읽기 쉽네요. 많이 배웁니다.

2024-09-25 01:46 UTC, haeum808 commented on app/src/main/java/woowacourse/shopping/ShoppingApplication.kt
>  class ShoppingApplication : Application() {
ShoppingApplication에 많은 코드가 있는데 Module Class같은 것을 만들어서 DepdencyInjector에 보내서 그안에서 이러한 일들을 해주면 어떨까요?

2024-09-25 01:46 UTC, haeum808 commented on di/src/main/java/com/woowacourse/di/DependencyInjector.kt
> +        scope: Any? = null,
Scope.None 같은 것을 추가해서 디폴트 파라미터로 넣으면 어떨까요?

2024-09-26 08:54 UTC, hxeyexn commented on app/src/main/java/woowacourse/shopping/ui/product/MainViewModel.kt
> +    }
안녕하세요~ 레아 !🧚

`LifeCycleTracker`에서 처리하는 방식으로 변경해보았습니다!
[033232c](https://github.com/woowacourse/android-di/pull/142/commits/033232c4992dcfcb27b46f7dceb1f4208cfe21f4)

2024-09-26 08:56 UTC, hxeyexn commented
안녕하세요! 해음~ 
전체적으로 코드를 수정해보다가 DateFormatter와 관련된 로직은 아직 다 구현하지 못했습니다...
오류가 계속 발생하는 데 원인을 아직 못 찾았어요.. 

지금 영어 수업을 가야해서 코멘트에 답변은 꼭 추후에 남겨놓도록 하겠습니다 ㅠㅠ 죄송합니다 ㅠㅠㅠㅠ

2024-09-26 10:13 UTC, hxeyexn commented on app/src/main/java/woowacourse/shopping/ui/product/MainViewModel.kt
> +    }
```kotlin
class CartViewModel : LifecycleAwareViewModel() {
    ...
}

abstract class LifecycleAwareViewModel : ViewModel() {
    override fun onCleared() {
        DependencyContainer.clearViewModelInstances()
    }
}
```
처음에는 위와 같이 구현했었는 데 `CartViewModel`이 `ViewModel()`이 아닌 `LifecycleAwareViewModel() `를 상속받고 있는게 어색하다고 느꼈습니다..!
대부분의 사용자는 ViewModel()을 상속받아 사용하는 것을 기본으로 기대할 텐데 이 대신 `LifecycleAwareViewModel()`를 사용하게 한다면 사용자 입장에서 내부 코드를 뜯어보지 않는 이상 기존 ViewModel()을 사용하지 않는지 의문을 가질 수도 있다고 생각했습니다.
그래서 `LifeCycleTracker`에서 `ViewMode`l의 `addCloseable`를 사용해 처리하도록 변경했는데 혹시 레아라면 어떤 방식으로 설계하실 지 여쭤봐도 될까용..?

2024-09-26 10:14 UTC, hxeyexn commented on app/src/main/java/woowacourse/shopping/ui/product/MainViewModel.kt
> +    }
해음의 생각도 궁금하네요..!! 🥹

2024-09-26 11:23 UTC, haeum808 commented on app/src/main/java/woowacourse/shopping/ui/product/MainViewModel.kt
> +    }
저도 좋다고 생각합니다. 그런데 viewmodel scope랑 activity scope가 나눠진건지 잘모르겠습니다!

2024-09-27 05:32 UTC, hxeyexn commented on app/src/main/java/woowacourse/shopping/GlobalViewModelFactory.kt
>  class GlobalViewModelFactory : ViewModelProvider.Factory {
ViewModelFactory도 DI 모듈에 있는 게 훨씬 자연스럽겠네요! DI 모듈로 이동시켰습니다~
[4aa6b88](https://github.com/woowacourse/android-di/pull/142/commits/4aa6b88bf98c73fab66116830329042696177d8d)

2024-09-27 05:37 UTC, hxeyexn commented on di/src/main/java/com/woowacourse/di/DependencyInjector.kt
> +        scope: Any? = null,
LifeCycle 에 따른 인스턴스 소멸 방식을 변경하면서 scope 매개변수를 제거하였습니다!
[36ef7ac](https://github.com/woowacourse/android-di/pull/142/commits/36ef7ac00de68f490ec391fea0ee50fd72d36af2)

2024-09-27 05:42 UTC, hxeyexn commented on app/src/main/java/woowacourse/shopping/ShoppingApplication.kt
>  class ShoppingApplication : Application() {
DIModule에서 필요한 인스턴스를 만들어주고 ComponentRegister 객체를 만들어 인스턴스를 등록해주는 역할을 하도록 변경했습니다!

2024-09-27 05:43 UTC, hxeyexn commented on di/src/main/java/com/woowacourse/di/DependencyInjector.kt
> +class DependencyInjector {
감사합니다! 네이밍은 항상 어려운 것 같아요 🥲

2024-09-27 15:00 UTC, merged