[호두] 자동 DI 미션 4단계 제출합니다
woowacourse/android-di pull request #144
Opened 2024-09-23 09:16 UTC by Junyoung-WON

아직 모든 요구사항을 만족하지 못했어요.......................
구현을 하다 말아서 현재 제대로 동작하지 않습니다.
최대한 오늘 중으로 구현을 완성하고 요구사항을 모두 만족시키려 합니다.
시간이 늦었기에 우선 PR 보내드려요!

아래는 제이슨이 남겨주신 질문에 대한 대답입니다.
### 질문
- 내가 만든 것은 라이브러리인가? 프레임워크인가? : 지금 분리된 모듈은 안드로이드에 대한 의존성이 강해서 라이브러리 보다는 프레임워크에 조금 더 가까워진 것 같아요.
- 내가 만든 것은 서비스 로케이터인가? DI인가? : DI 라고 생각합니다.
- 내가 만든 것은 자동 DI인가? 수동 DI인가? : 반자동입니다... 일부 의존성은 인스턴스를 직접 생성하여 넣어주는 작업이 있습니다.
  - 안드로이드 애플리케이션의 구조적 한계 : Lifecycle 관리가 어렵다..?
  - 그런데 사용자에게 맡기는 게 자연스러운 걸까? : 질문을 이해를 못했어요....! 사용자에게 맡긴다는 것이 안드로이드 어플리케이션의 구조적인 한계 때문에, 완전한 자동 DI를 만드는 것이 어렵다는 것으로 이해하였는데, 잘 모르겠습니다. 이해한 문맥으로 답을 하자면, 까다롭기 때문에 더욱 사용자(개발자)에게 맡기는 것이 자연스럽다고 생각합니다.

2024-09-24 07:30 UTC, sh1mj1 requested changes
호두, 정말 고생 많았습니다!!!!

새벽까지 엶심히 구현해서 굉장히 고생이 많으셨을 것 같아요!!
부족한 제가 지금으로써는 전체적인 구조가 크게 이상한 것 같지는 않습니다.
그래서 전체적인 구조 관련 리뷰는 아직 제대로 못 남겼네요.

저도 제 미션을 더 진행하면서 종종 들러서 구조 관련해서 코멘트를 더 남길 부분이 있나 확인해보겠습니다!!!

화이팅이야~
P.S 날씨가 서늘해졌는데 감기 조심하시오

2024-09-24 07:30 UTC, sh1mj1 commented on di/src/main/java/woowacourse/shopping/di/LifecycleAwareDependencyInjector.kt
> +    private inline fun <reified T : Annotation> KProperty<*>.checkAnnotation(): Annotation? {
이 함수 너무 잘 마음에 드네요 ㅋㅋ 👍👍👍👍

2024-09-24 07:30 UTC, sh1mj1 commented on di/src/main/java/woowacourse/shopping/di/ApplicationDependencyContainer.kt
> +        lifecycleAware: LifecycleAwareAnnotation,
LifecycleAwareAnnotation 을 KClass<*> 타입으로 하고, typealias 를 사용하셨군용
이렇게 해볼 생각은 못했는데 신기하네요

LifecycleAwareAnnotation 을 KClass<*>? 타입으로 한 것과,
Annotation 타입으로 해서 hasAnnotation 을 사용하는 것, 
혹은 원시값 표장하여 하나의 클래스로 만드는 것은 어떤 장,단이 있을까요?

2024-09-24 07:30 UTC, sh1mj1 commented on di/src/main/java/woowacourse/shopping/di/ApplicationDependencyContainer.kt
> +                lifecycleOwner?.lifecycle?.addObserver(ComponentLifecycleObserver {
`ComponentLifecycleObserver` 라는 이름만으로는 람다 파라미터가 무엇인지 예상하기 힘듭니다.
여기도 named argument 를 사용하면 파악하기 더 쉬울 것 같아요

2024-09-24 07:30 UTC, sh1mj1 commented on di/src/main/java/woowacourse/shopping/di/ComponentLifecycleObserver.kt
> +class ComponentLifecycleObserver(
`ComponentLifecycleObserver` 과 `ViewModelLifeCycleObserver` 가 있네요.
`ComponentLifecycleObserver` 에 onCreate 파라미터도 추가해서 이를 `ViewModelLifeCycleObserver` 를 사용하는 곳도 이 클래스를 사용하도록 할 수 있지 않을까요?

2024-09-24 07:30 UTC, sh1mj1 commented on di/src/main/java/woowacourse/shopping/di/ComponentDependencyProvider.kt
단순히 set 과 get 관련 함수만 존재한다면, 
implementationClass 와 dependencyInstance 를 생성자 파라미터로 하는 것이 낫지 않나요?

ApplicationDependencyContainer 의 setDependency 함수같은 곳의 구현이 개선될 수 있을 것 같아요.
```kotlin
val dependencyProvider = ComponentDependencyProvider()
dependencyProvider.setDependency(implementation)
dependencyStorage[dependency to qualifier] = dependencyProvider
```

2024-09-26 01:02 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/shopping/ui/MainViewModel.kt
> +    @ApplicationLifecycleAware
그런 방법도 있겠군요!! Enum 등의 상수로 관리한다면, 하나의 어노테이션으로 더 다양한 Lifecycle 을 나타낼 수도 있겠네요~

제가 여러 어노테이션을 만들었던 이유는 크게 아래 두 가지 이유 때문이었습니다!
### 개발자의 실수를 줄일 수 있다
어노테이션을 따로 구분하여 두는 것이 의미 전달이 더 명확할 것 같았고,
그래서 라이브러리를 사용하는 사용자 입장에서는 더 명시적인 방법이라 생각했습니다.
- `@FieldInject`, `@FieldInject(ActivityScope)`, `@FieldInject(ViewModelScope)` : 어떨 때는 프로퍼티가 없고 어떨때는 없는 것이 처음 보는 사용자 입장에서는 혼란스러울 수 있을 것 같아요. 프로퍼티가 꼭 필요한 것인가? 무엇을 넣어줘야하지?
- `@ApplicationScope`, `@ViewModelScope` : 어노테이션 이름 자체에 명시적으로 나타내어 혼란을 줄일 수 있을 것이라 생각했습니다!

### Lifecycle을 따르는지 확인하고 observing시키는 책임을 분리
**의존성 주입이 필요한지 확인** 하는 책임과 **주입될 의존성이 Lifecycle에 종속되는지를 확인** 하는 책임을 분리할 수 있지 않을까 하여 어노테이션을 따로 만들었습니다!
물론 구현하다보니 분리는 커녕 거기서 거기인 느낌이 강해지긴 했어요,,

2024-09-26 01:39 UTC, Junyoung-WON commented on di/src/main/java/woowacourse/shopping/di/ApplicationDependencyContainer.kt
> +typealias ClassQualifier = Pair<DependencyType, AnnotationQualifier>
별다른 이유는 있지 않았습니다...!😅 데이터 클래스로 만들 생각을 못했던 것 같아요.
데이터 클래스로 두는게 `Pair`를 사용하는 것 보다는 더 명시적이고 의미전달도 잘 되겠네요~

심지 피드백을 보고 한가지 궁금한 점이 생겼어요!
data class로 만들게 된다면, 이 class 에게 부여할 수 있는 역할이 무엇이 있을까요?
의존성 타입(KClass)와 어노테이션으로 둔 Qualifier(KAnnotatedElement)의 쌍으로서 단순히 의존성 맵에서의 키 역할을 하는데,
클래스로 둔다면 어떠한 책임을 맡길 수도 있을 것 같은데, 잘 생각이 안나네요!
심지도 혹시 함께 고민해줄 수 있나요?!

2024-09-26 01:45 UTC, Junyoung-WON commented on di/src/main/java/woowacourse/shopping/di/DependencyInjectedActivity.kt
> +abstract class DependencyInjectedActivity(application: DependencyInjectedApplication) :
저도 심지의 의견에 동의해요...!!
다른 크루들의 코드도 참고해보았을 때 _제일 깔끔하게 activity의 의존성 주입을 할 수 있겠구나_ 해서 참고하여 만들었지만, 한번 뿐인 상속 기회를 빼앗는다는 것이 제일 큰 문제점같습니다!
이렇게 되면 제 프레임워크를 사용하는 사용자는 개발에 있어 더욱 큰 제약을 받을지도 모르겠어요.

> application 과 activity 의 관계를 생각하면 application을 생성자 파라미터로 받는 게 부자연스러워보여요.

이 부분은 제가 너무 무식하게 구현한 것 같네요,,,, 😟 안드로이드 개발자 해도 되나,,,

2024-09-26 01:47 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/shopping/ui/cart/DateFormatter.kt
> +class DateFormatter(@ApplicationContext context: Context) {
Activity Lifecycle에 유지되긴 합니다...!
다만 시간이 없어서 activity의 context를 가져올 방법을 구현하지 못해서,,
급한대로 application context를 주입받게 했습니다 😱

이 부분도 꼭 개선하겠습니다!

2024-09-26 01:48 UTC, Junyoung-WON commented on app/src/main/java/woowacourse/shopping/ui/util/ReflectiveViewModelFactory.kt
>      }
뷰모델 팩토리를 직접 만들지 않고도 뷰모델을 생성할 수 있도록 코드를 개선해볼게요!
viewModels 메서드를 참고해서 만들어볼 수 있을 것 같아요!

2024-09-26 01:59 UTC, Junyoung-WON commented on di/src/main/java/woowacourse/shopping/di/ComponentLifecycleObserver.kt
> +class ComponentLifecycleObserver(
으음, 질문의 의도를 제대로 이해하지 못했어요!
`ComponentLifecycleObserver`에도 `onCreate()` 콜백 파라미터를 추가하면 
굳이 `ViewModelLifecycleObserver` 를 사용하지 않아도 될 것이라는 뜻인가요??

2024-09-26 08:19 UTC, Junyoung-WON commented on di/src/main/java/woowacourse/shopping/di/ComponentDependencyProvider.kt
위와 같은 구현이라면, DependencyProvider 인터페이스를 제거하고 클래스로 두는 것이 좋을 것 같아요...!
인터페이스를 굳이 만들어서 사용한 이유는 혹여나 다른 구현의 DependencyProvider를 만들 수도 있지 않을까 하는 확장성 측면에서였는데,
현재는 ComponentDependencyProvider 하나만을 만들어 사용하고 있으니, 인터페이스를 만들어 구현한 것이 오히려 구현에 제약을 주었다는 생각이 들어요. (getter, setter 메서드를 강제하게 됨)
어느 구현이 좋은 방향일지 아직 감이 잡히지 않는데, 심지의 생각은 어떤가요?

2024-09-26 08:27 UTC, Junyoung-WON commented
안녕하세요, 심지!!
엉망진창 구현에 읽기 어려운 코드였을텐데도, 정성된 피드백 너무 감사드립니다...😭
생각과 고민은 많은데 이를 코드로 간결하게 나타내는 것이 어렵네요...
아직 제 스스로가 생각하기에도 명확한 해답을 내리지 못했다는 증거이기도 한 것 같습니다.
아무래도 공부가 부족했던 것 같아요! 겉할기식 공부가 이런 난잡한 코드를 만들어낸 것이 아닐까 생각합니다.
더 깊이 파고들어볼 필요가 있을 것 같습니다.

아래는 주요 수정 내용을 간략하게 정리해보았습니다!
- `ClassQualifier` : `typealias`에서 `data class`로 변경
- di 모듈 패키지 분리
- 뷰모델 생성 확장함수 작성 및 적용
- 생명주기 의존성에 관한 테스트코드 작성

**제이슨의 질문**에 대한 답은 내일 안에 다시 작성해보려합니다!

2024-09-29 20:03 UTC, sh1mj1 commented on app/src/main/java/woowacourse/shopping/ui/MainViewModel.kt
> +    @ApplicationLifecycleAware
설득력 있는 방법인 것 같아요! 👍👍

2024-09-29 20:21 UTC, sh1mj1 commented on di/src/main/java/woowacourse/shopping/di/ApplicationDependencyContainer.kt
> +typealias ClassQualifier = Pair<DependencyType, AnnotationQualifier>
`ClassQualifier` 인스턴스 중에서 같은 프로퍼티를 가지게 된다고 하면,
`ClassQualifier` 가 인스턴스들의 팩토리 역할을 하도록 할 수 있지 않을까요?

Lotto 미션에서 LottoNumber 클래스가 LottoNumber 인스턴스들을 캐싱해서 `LottoNumber` 클래스가 인스턴스들의 팩토리 역할을 했던 것처럼요!

하지만 이 미션에서는 같은 `ClassQualifier`  인스턴스들을 자주 만들게 될지는 잘 모르겠네요..
이런 역할을 부여하는 것 외에는 잘 생각이 나질 않네요.. ㅎ

하지만 저는 data class 로 만듦으로써 명시적 의미전달과 `toString()` 등의 메서드를 사용할 수 있음의 역할로 충분하다고 생각해요

2024-09-29 20:22 UTC, sh1mj1 commented on di/src/main/java/woowacourse/shopping/di/DependencyInjectedActivity.kt
> +abstract class DependencyInjectedActivity(application: DependencyInjectedApplication) :
직접 안드로이드 DI 프레임워크를 구현하면서 안드로이드 종속성 때문에 상속이 아니면 꽤 힘들더라구요... ㅠㅜ

2024-09-29 20:29 UTC, sh1mj1 commented on di/src/main/java/woowacourse/shopping/di/ComponentLifecycleObserver.kt
> +class ComponentLifecycleObserver(
넵, 코틀린에서는 프로퍼티 기본 값을 설정해줄 수 있으니 같은 클래스로부터 상황에 맞게 인스턴스를 다르게 생성할 수 있을 것 같았습니다.

그런데 지금 보니, 그러한 상황이더라도, 클래스를 다르게 두는 게 더 명시적인 것 같네요 ㅎㅎ

2024-09-29 20:35 UTC, sh1mj1 commented on di/src/main/java/woowacourse/shopping/di/ComponentDependencyProvider.kt
저는 이 부분에서는 interface 를 만들지 않아도 된다고 생각하기는 했습니다.

하지만, 직접 코드를 고쳐보면서 해보지 않는 이상, 섣불리 무엇이 더 좋은 구현 방향이라고 단언하기가 힘드네요...
이 부분을 인터페이스로 두지 않고 다시 미션을 진행해본다면 답이 나올 수 있을 것 같긴 합니다.

저도 해보고 싶은데 시간이 없어어요 ㅠㅜ 일정이 참 빠듯하네요 ㅠㅠㅜㅠㅜ

2024-09-29 20:42 UTC, sh1mj1 commented
테스트도 꼼꼼히 작성해주셨군요!!!

피드백도 많이 반영하시느라 고생 많으셨습니다
저는 미션에서 액티비티 상속을 하지 않고 구현했습니다. 
호두는 액티비티 상속으로 구현해서 저와 다른 코드여서 더욱 유익하게 본 것 같습니다!!
(저는 그래서 더욱 서비스 로케이터처럼 구현되었어요 ㅠㅜ)

리뷰가 많이 늦어서 죄송합니다
생각해보실 점들 리뷰로 남겨두었습니다!
새로 변경한 부분보다는 호두가 제 생각을 물어본 것들 위주로 남겨두었어요

호두 코드를 리뷰하게 되어서 좋았습니다. 다음 미션과 프로젝트도 화이팅입니다!!!!!!!!

2024-09-29 20:42 UTC, sh1mj1 approved these changes
테스트도 꼼꼼히 작성해주셨군요!!!

피드백도 많이 반영하시느라 고생 많으셨습니다
저는 미션에서 액티비티 상속을 하지 않고 구현했습니다.
호두는 액티비티 상속으로 구현해서 저와 다른 코드여서 더욱 유익하게 본 것 같습니다!!
(저는 그래서 더욱 서비스 로케이터처럼 구현되었어요 ㅠㅜ)

리뷰가 많이 늦어서 죄송합니다
생각해보실 점들 리뷰로 남겨두었습니다!
새로 변경한 부분보다는 호두가 제 생각을 물어본 것들 위주로 남겨두었어요

호두 코드를 리뷰하게 되어서 좋았습니다. 다음 미션과 프로젝트도 화이팅입니다!!!!!!!!

2024-09-29 20:43 UTC, merged