[뽀또] 1단계 자동 DI 미션 제출합니다
woowacourse/android-di pull request #18
Opened 2023-09-04 17:00 UTC by hyunji1203

하티~~~!! 안녕하세요!!!! 

이번 미션 리뷰어가 하티라서 너무너무 행복합니다🫶 

그리고 DI 자체를 처음 접해봐서 공부 후 구현하느라 시간이 좀..많이… 걸렸습니다ㅎㅎ

이번 미션 리뷰 잘부탁드립니다!! 🥰

## 구현 설명

- Repository의 구현체들을 생성해 갖고 있는 `DataModule` 클래스를 생성하였습니다
    - 해당 클래스는 현재 object class로 구현이 되어 있는데 추후 미션을 진행하면서 object가 아닌 그냥 class 바꾸는 건 어떨까 고민중입니다.
- 자동으로 의존성을 주입해주는 `AutoDependencyInjector` Class 를 생성하였습니다.
    - `matchParameterType` 함수는 `DataModule` 클래스의 프로퍼티와 `inject` 함수의 인자로 받은 클래스의 프로퍼티의 타입을 비교해, 같은 타입이라면 해당 모듈을 추가해 최종적으로 필요한 모든 모듈들을 반환해주는 메소드 입니다.
    - `inject` 함수에선 필요한 파라미터가 없는 경우라면 에러를 날리도록 하였습니다.
- `Application` 을 상속하는 `ShoppingApplication` 에서는 `AutoDependencyInjector` 의 구현체를 생성하였습니다.
- `ViewModelFactory` 에서는 `AutoDependencyInjector` 의 `inject` 함수를 사용해 ViewModel를 생성하도록 구현하였습니다.

- 선택 요구 사항들은 현재 지키지 못하였지만 차차 채워나가겠습니다!

## 요구사항

### 기능 요구 사항

생성자 주입 - 수동

- [x]  테스트하기 어렵다.
- [x]  Repository 객체를 교체하기 위해 또다른 객체를 만들어 바꿔줘야 한다. 즉, ViewModel에 직접적인 변경사항이 발생한다.

생성자 주입 - 자동

- [x]  ViewModel에서 참조하는 Repository가 정상적으로 주입되지 않는다.
- [x]  Repository를 참조하는 다른 객체가 생기면 주입 코드를 매번 만들어줘야 한다.
    - [x]  ViewModel에 수동으로 주입되고 있는 의존성들을 자동으로 주입되도록 바꿔본다.
    - [x]  특정 ViewModel에서만이 아닌, 범용적으로 활용될 수 있는 자동 주입 로직을 작성한다. (MainViewModel, CartViewModel 모두 하나의 로직만 참조한다)
    - [x]  100개의 ViewModel이 생긴다고 가정했을 때, 자동 주입 로직 100개가 생기는 것이 아니다. 하나의 자동 주입 로직을 재사용할 수 있어야 한다.
- [x]  장바구니에 접근할 때마다 매번 CartRepository 인스턴스를 새로 만들고 있다.
    - [x]  여러 번 인스턴스화할 필요 없는 객체는 최초 한 번만 인스턴스화한다. (이 단계에서는 너무 깊게 생각하지 말고 싱글 오브젝트로 구현해도 된다.)

### 선택 요구 사항

- [ ]  TDD로 DI 구현
- [ ]  Robolectric으로 기능 테스트
- [ ]  ViewModel 테스트
- [ ]  모든 도메인 로직, Repository 단위 테스트

### 프로그래밍 요구 사항

- [x]  사전에 주어진 테스트 코드가 모두 성공해야 한다.
- [x]  Annotation은 이 단계에서 활용하지 않는다.

2023-09-05 06:56 UTC, sujin9 requested changes
안녕하세요, 뽀또! ;)
저도 리뷰이가 뽀또라서 너무너무 행복해용 💓

1단계 깔끔하게 잘 구현해주셨어요!!
몇 가지 생각해볼 만한 점들을 남겨보았으니 확인 부탁드려요 ㅎㅎ
더 궁금한 사항이나 얘기하고 싶은 점들이 있다면 얘기해주세요! ;)

2023-09-05 06:56 UTC, sujin9 commented on app/src/main/java/woowacourse/shopping/di/inject/AutoDependencyInjector.kt
> +            val argument = modules.first { it.returnType == parameter.type }
만약 modules 안에 찾고자 하는 파라미터 타입의 인스턴스가 없다면 어떤 일이 일어날까요??

2023-09-05 06:56 UTC, sujin9 commented on app/src/main/java/woowacourse/shopping/di/inject/AutoDependencyInjector.kt
> +    private fun <T : Any> matchParameterType(clazz: KClass<T>): T? {
`matchParameterType` 함수는 nullable한 객체를 반환하도록 구현이 되어있네요! 혹시 이렇게 구현하신 이유가 있으실까요??

제 의견으로는, 현재 함수 내부를 보면, nullable한 타입의 객체가 많고, 실제로 `?.` 연산자가 많이 사용되고 있어요. 이러한 경우, 오류가 발생할 가능성이 있는 지점들이 많아지고, 예상하지 못한 오류가 발생할 가능성이 높아지게 될 것 같아요. 그래서 좀 더 안전한(?) 코드로 개선해보아도 좋을 것 같아 제안드립니다! :)

2023-09-05 06:56 UTC, sujin9 commented on app/src/main/java/woowacourse/shopping/ui/MainActivity.kt
> +        ViewModelProvider(this, ViewModelFactory())[MainViewModel::class.java]
공통으로 사용할 수 있도록 클래스를 잘 만들어주셨네요! 코드가 간결하고 가독성도 좋아요!! 😆 👍

2023-09-05 06:56 UTC, sujin9 commented on app/src/main/java/woowacourse/shopping/di/inject/AutoDependencyInjector.kt
> +        private const val INJECT_ERROR_MESSAGE = "주입 할 생성자가 존재하지 않습니다."
오류 메시지 상수화까지 꼼꼼하게 해주셨네요!! 👍 👍

2023-09-05 12:13 UTC, hyunji1203 commented on app/src/main/java/woowacourse/shopping/di/common/ViewModelFactory.kt
> +        return ShoppingApplication().autoDependencyInjector.inject(modelClass)
좋아요~!
기존 방식으로 구현하면 불필요한 인스턴스가 생성된다는 문제가 생깁니다!
따라서 이런 문제를 해결하기 위해 `ShoppingApplication`의 companion object에 해당 `autoDependencyInjector`를 선언해주었습니다!

2023-09-05 12:28 UTC, hyunji1203 commented on app/src/main/java/woowacourse/shopping/di/inject/AutoDependencyInjector.kt
> +    private fun <T : Any> matchParameterType(clazz: KClass<T>): T? {
원래의 구현 의도는, `matchParameterType `에서 nullable 한 객체를 반환 후 이에 대한 null 오류 처리를 `inject` 판단하도록 한 것 입니다!

하지만 하티의 말을 들어보니 굳이 예상치 못한 오류가 생길 수 있는 가능성을 높이는 불안정한 코드보다 안전한 코드로 구현하는 것이 좋다고 판단해 수정하였습니다~~!!

2023-09-05 12:31 UTC, hyunji1203 commented on app/src/main/java/woowacourse/shopping/di/inject/AutoDependencyInjector.kt
> +            val argument = modules.first { it.returnType == parameter.type }
modules 안에 찾고자 하는 파라미터 타입의 인스턴스가 없다면 `IllegalArgumentException`에러를 던지도록 로직을 추가하였습니다!

2023-09-06 05:47 UTC, hyunji1203 commented
리뷰 반영 하면서 부가적인 리팩토링 및 ViewModel 테스트도 같이 추가했습니다 😄

2023-09-06 08:51 UTC, sujin9 approved these changes
고생했어요 뽀또 !!
테스트까지 꼼꼼하게 추가해주셨네요 👍 👍 
몇 가지 더 궁금한 점들은 코멘트로 남겨뒀어요 ;)
다음 스텝도 파이팅입니다 ~ 🌹

2023-09-06 08:51 UTC, sujin9 commented on app/src/main/java/woowacourse/shopping/di/Module.kt
> +interface Module
`Module`로 추상화해주신 이유가 무엇인지 궁금해요!

2023-09-06 08:51 UTC, sujin9 commented on app/src/main/java/woowacourse/shopping/di/inject/AutoDependencyInjector.kt
> +            arguments.add(argument.getter.call(DataModule)!!)
`private val module: Module` 프로퍼티가 존재하는데,
명시적으로 DataModule을 사용해주신 이유가 있을까요?

2023-09-06 08:51 UTC, sujin9 commented on app/src/main/java/woowacourse/shopping/ui/MainActivity.kt
> +        ViewModelProvider(this, ViewModelFactory)[MainViewModel::class.java]
`ViewModelProvider(this, ViewModelFactory)[MainViewModel::class.java]`
`ViewModelProvider(this, ViewModelFactory)[CartViewModel::class.java]`
좀 더 욕심을 내보면, 이 두 코드도 겹치는 부분을 제거하여 간결하게 표현해볼 수 있을 것 같은데요!?
이 부분은 미션을 진행하시면서 여유가 된다면 한 번 해보셔도 좋을 것 같다는 조심스러운 제안입니다 ~ ㅎㅎ

키워드: `ViewModelLazy`

2023-09-06 08:52 UTC, merged

2023-09-07 07:43 UTC, hyunji1203 commented on app/src/main/java/woowacourse/shopping/di/Module.kt
> +interface Module
지금은 고려하지 않아도 되는 부분이지만,
훗날 repository가 담긴 module이 아닌, 다른 것이 담긴 module이 생긴다고 가정할 때 그 때의 확장성을 위해 추상화를 진행했습니다.