[수달] 1단계 자동 DI 미션 제출합니다
woowacourse/android-di pull request #21
Opened 2023-09-05 06:16 UTC by otter66

안녕하세요 스캇! 
스캇을 리뷰어로 만나게되어 영광입니다!!! 
리뷰 잘 부탁드리겠습니다~!!!

해당 커밋들에 대한 코드 리뷰를 해주시면 좋을 것 같습니다! (코드 컨벤션을 맞추는 불필요한 커밋이 분리되었습니다!)

## 자동 DI 로직
- **ActivityViewModelLazy.kt**
  - ViewModelFactory의 로직을 가집니다. Activity에서 by viewModels()의 형태로 ViewModel을 생성할 수 있도록 합니다.
  - ShoppingApplication이 가진 Injecter 객체의 inject() 메서드를 통해 ViewModel이 필요로 하는 의존성을 주입합니다.   
- **Injector**
  - Repository와 같은 객체를 생성하는 Module을 주입 받습니다. 
  - 의존성을 주입받아야 하는 ViewModel과 같은 객체의 생성자에 알맞게 Module을 사용해 의존성을 주입해줍니다.

## 미션 요구사항 진척도
### 생성자 주입 - 수동   
다음 문제점을 해결한다.   
- [x]  테스트하기 어렵다.
- [x]  Repository 객체를 교체하기 위해 또다른 객체를 만들어 바꿔줘야 한다. 즉, ViewModel에 직접적인 변경사항이 발생한다.

### 생성자 주입 - 자동
다음 문제점을 해결한다.
- [x]  ViewModel에서 참조하는 Repository가 정상적으로 주입되지 않는다.
- [x]  Repository를 참조하는 다른 객체가 생기면 주입 코드를 매번 만들어줘야 한다.
    - [x]  ViewModel에 수동으로 주입되고 있는 의존성들을 자동으로 주입되도록 바꿔본다.
    - [x]  특정 ViewModel에서만이 아닌, 범용적으로 활용될 수 있는 자동 주입 로직을 작성한다. (**`MainViewModel`**, **`CartViewModel`** 모두 하나의 로직만 참조한다)
    - [x]  100개의 ViewModel이 생긴다고 가정했을 때, 자동 주입 로직 100개가 생기는 것이 아니다. 하나의 자동 주입 로직을 재사용할 수 있어야 한다.
- [x]  장바구니에 접근할 때마다 매번 **`CartRepository`** 인스턴스를 새로 만들고 있다.
    - [x]  여러 번 인스턴스화할 필요 없는 객체는 최초 한 번만 인스턴스화한다. (이 단계에서는 너무 깊게 생각하지 말고 싱글 오브젝트로 구현해도 된다.)

### 선택 요구 사항
- [ ]  TDD로 DI 구현
- [x]  Robolectric으로 기능 테스트
- [x]  ViewModel 테스트
- [x]  모든 도메인 로직, Repository 단위 테스트

### 프로그래밍 요구 사항
- [x]  사전에 주어진 테스트 코드가 모두 성공해야 한다.
- [x]  Annotation은 이 단계에서 활용하지 않는다.

2023-09-05 08:03 UTC, chws0508 requested changes
안녕하세요 수달!!
너무 잘 구현해주셔서 리뷰할 것이 많지 않네요 ㅎㅎ
깔끔한 테스트 코드도 인상적이었습니다!
몇가지 코멘트를 남겼으니, 확인해주시고 다시 리뷰 요청 해주세요!!

2023-09-05 08:03 UTC, chws0508 commented on app/src/test/java/woowacourse/shopping/provider/DefaultViewModelTest.kt
> +    }
저는 개인적으로 두 함수는 아무런 내용이 없다면 없애도 될 것 같아요.
테스트 파일에서 ovveride 로 구현하는 것보다, 직접 Before 와 After  어노테이션을 붙여주는것이 가독성에 좋아보입니다.

2023-09-06 10:02 UTC, otter66 commented on app/src/test/java/woowacourse/shopping/provider/Fake.kt
> +private class FakeCartRepository : woowacourse.shopping.repository.CartRepository {
같은 네이밍을 사용하는 클래스와 함수가 함께 사용될 것을 걱정하였는데, `FakeCartRepository` 객체와 이것을 반환하는 `CartRepository`를 사용하게 되며 불필요해졌네요! 알려주세셔 감사합니다!

2023-09-06 10:10 UTC, otter66 commented on app/src/test/java/woowacourse/shopping/provider/Fake.kt
> +private class FakeCartRepository : woowacourse.shopping.repository.CartRepository {
아! 혹시 이 부분에 대해서 고민이 있는데 함께 고민해주실 수 있을까요!

현재 코드에서는 Domain test 모듈과 App test 모듈에 완정히 일치하는 Fake 객체가 있습니다.
차후에 Domain, App 모듈에 따라 차이점이 생길 수는 있지만, 여전히 동일한 기능들이 있을 것이라 생각합니다.
때문에 **Doamin test 모듈에 있는 객체나 함수를 App test 모듈에서도 사용하고 싶습니다!**

그러나 현재 gradle에 도메인 모듈에 대한 의존성이 추가되어 있음에도 App test 모듈에서 Domain test 모듈의 기능을 사용할 수 없습니다... 물론, `internal` 접근제어자도 제거해주었습니다! 

이 부분에 대해 함께 고민해주실 수 있을까요!

2023-09-06 10:18 UTC, otter66 commented on app/src/test/java/woowacourse/shopping/provider/DefaultViewModelTest.kt
> +    }
좋은 것 같습니다!

2023-09-06 10:34 UTC, otter66 commented on app/src/main/java/woowacourse/shopping/di/injector/Injector.kt
> +                }
매번 toString을 해줄 필요가 없어졌네요!

2023-09-06 12:11 UTC, otter66 commented on app/src/main/java/woowacourse/shopping/di/ActivityViewModelLazy.kt
> +
[ViewModelStoreOwner](https://developer.android.com/reference/androidx/lifecycle/ViewModelStoreOwner)라는 것이 있었네요! 
뷰모델을 가질 수 있는 객체는 모두 해당 인터페이스를 상속받아 구현한 객체들이네요!!! 때문에 ViewModel을 생성하는 로직을 가지는 확장함수는 해당 인터페이스의 확장함수로 만들어주면 좋을 것 같습니다! 
수정하였습니다!

2023-09-06 12:14 UTC, otter66 commented
스캇! 리뷰 반영하였습니다! 
https://github.com/woowacourse/android-di/pull/21#discussion_r1317058439
고민중인 부분이 있습니다! 혹시 참고할만한 키워드가 있을까 여쭤봅니다!

2023-09-07 02:01 UTC, chws0508 commented on app/src/test/java/woowacourse/shopping/provider/Fake.kt
> +private class FakeCartRepository : woowacourse.shopping.repository.CartRepository {
App Test 모듈 gradle 에서 Domain Test 모듈에 있는 객체를 사용할 방법은 잘 떠오르지 않네요 ㅎㅎ 
만약 중복 코드를 방지하고 싶다면,  test module 이 아닌 일반 모듈에 Fake 객체를 정의하는 방법이 있겠네요.

2023-09-07 02:05 UTC, chws0508 approved these changes

2023-09-07 02:07 UTC, merged

2023-09-07 02:07 UTC, chws0508 commented
잘 반영 해주셧네요!! 수달이 남긴 질문에 대해 개인적인 견해가 담긴 코멘트를 남겨놨습니다!! 2,3단계 때 봬요!