[토마스] 1단계 자동 DI 미션 제출합니다
woowacourse/android-di pull request #25
Opened 2023-09-05 08:12 UTC by ki960213

안녕하세요, 핑구!
리뷰어로 만나게 되어 반갑습니다 ✋ 

sheath라는 자동 DI 라이브러리를 만들었습니다. 현재는 코드 리뷰를 위해 모듈에 있습니다.
sheath의 자동 DI 원리를 간단하게 설명드리겠습니다.

1. `SheathApplication` 클래스를 상속받은 `Application` 객체가 생성되면 모든 패키지에서 `Component` 인터페이스 혹은 `Component`의 자식 인터페이스를 구현한 클래스를 찾습니다.
2. 찾은 클래스들 간의 의존성에 따라 순서대로 인스턴스를 생성하기 위해 위상 정렬 알고리즘을 사용하여 클래스 목록을 정렬합니다.
3. 정렬된 순서대로 인스턴스를 생성 후 싱글톤 컨테이너에 저장합니다.
4. `SheathApplication`은 싱글톤 컨테이너의 역할을 수행합니다.
5. `AndroidEntryPoint` 클래스를 상속받은 `Activtity` 클래스에서 특정 타입의 뷰 모델을 생성하려 할 때 그 뷰 모델이 종속 항목이 있다면 싱글톤 컨테이너에서 찾아서 주입 후 뷰 모델 객체를 생성합니다. 저희가 평소에 사용하던 `viewModels()` 메서드를 똑같이 사용하면 자동으로 싱글톤 컨테이너에서 종속 항목을 찾아서 주입해줍니다.

기능에 대한 설명은 [여기](https://github.com/ki960213/android-di/tree/step1#android-di)에서 더 확인하실 수 있습니다.

## 요구사항
### 기능 요구 사항
생성자 주입 - 수동

- [x] 테스트하기 어렵다.
- [x] Repository 객체를 교체하기 위해 또다른 객체를 만들어 바꿔줘야 한다. 즉, ViewModel에 직접적인 변경사항이 발생한다.

생성자 주입 - 자동

- [x] ViewModel에서 참조하는 Repository가 정상적으로 주입되지 않는다.
- [x] Repository를 참조하는 다른 객체가 생기면 주입 코드를 매번 만들어줘야 한다.
- [x] ViewModel에 수동으로 주입되고 있는 의존성들을 자동으로 주입되도록 바꿔본다.
- [x] 특정 ViewModel에서만이 아닌, 범용적으로 활용될 수 있는 자동 주입 로직을 작성한다. (MainViewModel, CartViewModel 모두 하나의 로직만 참조한다)
- [x] 100개의 ViewModel이 생긴다고 가정했을 때, 자동 주입 로직 100개가 생기는 것이 아니다. 하나의 자동 주입 로직을 재사용할 수 있어야 한다.
- [x] 장바구니에 접근할 때마다 매번 CartRepository 인스턴스를 새로 만들고 있다.
- [x] 여러 번 인스턴스화할 필요 없는 객체는 최초 한 번만 인스턴스화한다. (이 단계에서는 너무 깊게 생각하지 말고 싱글 오브젝트로 구현해도 된다.)

### 선택 요구 사항
- [x] TDD로 DI 구현
- [ ] Robolectric으로 기능 테스트
- [ ] ViewModel 테스트
- [ ] 모든 도메인 로직, Repository 단위 테스트

### 프로그래밍 요구 사항
- [x] 사전에 주어진 테스트 코드가 모두 성공해야 한다.
- [x] Annotation은 이 단계에서 활용하지 않는다.

## 리뷰어에게 하고 싶은 말
현재 시간이 없어서 `ClassesTopologicalSorter` 클래스의 코드가 많이 더럽습니다. 어지러우시면 이 클래스는 제외하고 리뷰해주셔도 괜찮습니다 😄

2023-09-05 14:35 UTC, pingu244 requested changes
토마스 1단계 미션 고생 많으셨습니다~!
TDD로 미션을 구현하셨다니 정말 대단합니다..👍
Readme를 상세히 작성해주셔서 전반적인 코드 이해에 도움이 되었습니다. 감사합니다!
개인적으로 궁금한 점에 대한 코멘트가 많으니 답글 부탁드려요~
확인해주시고 다시 리뷰요청 남겨주세요!

2023-09-05 14:35 UTC, pingu244 commented on sheath/src/main/java/com/ki960213/sheath/util/ClassesTopologicalSorter.kt
> +    }
sort()가 너무 많은 일을 하고 있어요!

2023-09-05 14:35 UTC, pingu244 commented on sheath/src/main/java/com/ki960213/sheath/util/ClassesTopologicalSorter.kt
> +    fun sort(classes: List<Class<*>>): List<Class<*>> {
개인적인 의견이니 가볍게 생각해주세요.
이 부분만이 아니라 전반적으로 코드들이 자바스러운 것 같아요.
Class대신 KClass를 사용하는 등 좀 더 코틀린스럽게 수정해보는 것은 어떨까요?

2023-09-05 14:35 UTC, pingu244 commented on sheath/src/main/java/com/ki960213/sheath/util/ClassesTopologicalSorter.kt
> +}
위에서 말했던 것처럼 KClass를 사용한다면 바로 primaryConstructor를 뽑아올 수 있어요!

2023-09-05 14:35 UTC, pingu244 commented on sheath/src/main/java/com/ki960213/sheath/SheathApplication.kt
> +        sortedClasses.forEach { container.add(InstanceGenerator.generate(it, container.toList())) }
코드를 잘 이해하지 못해 확인 차원에서 질문드립니다.
`InstanceGenerator.generate(it, container.toList())` 이 부분에서 container.toList()은 처음에 빈 값일텐데 어떻게 이 안에서 원하는 인스턴스를 찾을 수 있는 이유가
ClassesTopologicalSorter.sort()를 통해 위상정렬되어서 인건가요? 
빈 값이어도 생성될 수 있는 아이 먼저 반복문을 돌아 차곡차곡 쌓여 앞의 아이들을 기반으로 만들어지는 애들까지 만들어지는건가요?

2023-09-05 14:35 UTC, pingu244 commented on README.md
> +2. `Component`, `Repository` 인터페이스가 있습니다. `Repository`는 단지 특정 클래스가 리포지토리 패턴을 따른다는 것을 명시하기 위한 인터페이스입니다. 기능적으로는 `Component`든 `Repository`든 상관없이 싱글톤 컨테이너에 저장됩니다.
Repository라는 인터페이스를 굳이 만들 필요가 있을까요?

2023-09-07 07:01 UTC, ki960213 commented on sheath/src/main/java/com/ki960213/sheath/activity/AndroidEntryPoint.kt
> +    }
불필요한 public 함수를 노출하는 것보다는 함수가 길더라도 노출하지 않는 게 더 낫지 않을까요? 😢

2023-09-07 07:01 UTC, ki960213 commented on sheath/src/main/java/com/ki960213/sheath/activity/AndroidEntryPoint.kt
> +        )
불필요한 public 함수를 노출하는 것보다는 함수가 길더라도 노출하지 않는 게 더 낫지 않을까요? 😢

2023-09-07 07:02 UTC, ki960213 commented on sheath/src/main/java/com/ki960213/sheath/activity/AndroidEntryPoint.kt
> +abstract class AndroidEntryPoint : AppCompatActivity() {
동의합니다. 추후 애노테이션으로 변경할 예정입니다!

2023-09-07 07:03 UTC, ki960213 commented on sheath/src/main/java/com/ki960213/sheath/SheathApplication.kt
> +        sortedClasses.forEach { container.add(InstanceGenerator.generate(it, container.toList())) }
네 맞습니다 😊

2023-09-07 07:03 UTC, ki960213 commented on README.md
> +2. `Component`, `Repository` 인터페이스가 있습니다. `Repository`는 단지 특정 클래스가 리포지토리 패턴을 따른다는 것을 명시하기 위한 인터페이스입니다. 기능적으로는 `Component`든 `Repository`든 상관없이 싱글톤 컨테이너에 저장됩니다.
추후 LocalDataSource 애노테이션, RemoteDataSource 애노테이션 등이 생기면 Component 애노테이션만 붙이는 것보다 더 좋다고 생각합니다!

2023-09-07 07:27 UTC, pingu244 commented on sheath/src/main/java/com/ki960213/sheath/activity/AndroidEntryPoint.kt
> +    }
public 함수 안에 private 함수를 만들어주는 것은 어떨까요?

2023-09-07 07:30 UTC, pingu244 commented on sheath/src/main/java/com/ki960213/sheath/SheathApplication.kt
> +        sortedClasses.forEach { container.add(InstanceGenerator.generate(it, container.toList())) }
저는 위상정렬 이라는 단어도 이번 토마스를 통해 처음 알게되었어요ㅋㅋㅋ
의존성까지 생각하다니 정말 대단하네요 토마스!

2023-09-07 07:37 UTC, ki960213 commented on sheath/src/main/java/com/ki960213/sheath/activity/AndroidEntryPoint.kt
> +    }
그것도 불필요한 public 함수를 노출하는 것 아닌가요? 😢

2023-09-07 07:47 UTC, pingu244 approved these changes
토마스 고생하셨습니다~
더는 리뷰드릴 것이 없어 이만 머지하겠습니다!

2023-09-07 07:56 UTC, merged