[코건] 1단계 자동 DI 미션 제출합니다
woowacourse/android-di pull request #3
Opened 2023-09-02 17:42 UTC by DYGames

둘리 안녕하세요~

DI 라이브러리를 한번도 안 써봐서 어려웠네요.
자동 DI의 구현에서 제가 생각한 핵심 아이디어입니다.
- 전역에서 하나만 생성되어도 되는 의존은 `Dependencies` 인터페이스를 상속받는 클래스에서 관리한다.
- 의존 주입
  - Dependencies 클래스에서 의존을 검색하고 있을 경우 반환
  - 없을 경우 생성자 호출로 인스턴스 생성
    - 생성자 안의 의존은 다시 재귀적으로 의존 주입
  - 생성자 없을 시 예외 발생

0.5단계, 1단계 요구사항 모두 달성했습니다.
선택 요구 사항은 `TDD로 DI 구현` 제외 모두 달성했습니다.

추가적으로 자동 DI에 테스트도 작성했습니다.
테스트를 위해 전역 의존을 가변적으로 선택 할 수 있게 하고 여러 상황에 대해 테스트 코드를 다 작성했습니다.
근데 이 의존을 생성자 주입으로 하면 좋을 것 같은데 inject()가 object의 멤버 함수여서 어려웠습니다.
이때 문제점이 전역 의존이 코드의 아무곳에서나 변경 가능합니다. 이 부분에 대한 조언 주시면 감사하겠습니다.

감사합니다!

2023-09-03 09:07 UTC, hyemdooly reviewed
안녕하세요, 코건!
많은 고민을 하신 흔적이 보입니다! 이렇게 빠른 시간 안에 선택 사항까지 대부분 구현하시다니 대단해요 👍 
저와 방식이 조금 달라서 찾아가면서 읽느라 시간이 좀 걸렸어요. 덕분에 kotlin reflect가 따로 있는 것도 알았네요.
작동 원리 자체에 대해 피드백 드릴 부분은 딱히 생각나지 않았어요. DependencyInjector 테스트 코드는 상당히 인상 깊었습니다.
코건의 생각을 묻는 리뷰가 많은데 확인 부탁드려요~

2023-09-03 09:28 UTC, hyemdooly commented on app/src/main/java/woowacourse/shopping/di/DependencyInjector.kt
> +    lateinit var dependencies: Dependencies
코건이 고민 중인 부분 이 부분인거죠?
저도 같은 이유로 이 부분이 불편하긴 하네요.🤔

저는 dependencies가 바뀌지 않을 것이라고 생각해서 class 내부에 변수에 바로 꽂아줬는데요.
코건의 경우에는 dependencies가 바뀔 수도 있음을 고려한 것 같아요.

```kotlin
    companion object {
        private var di: DependencyInjector? = null

        fun newInstance(dependencies: Dependencies): DependencyInjector {
            di = DependencyInjector(dependencies)
            return di!!
        }
        fun instance(): DependencyInjector = di ?: throw IllegalArgumentException()
    }
```
이런 방식으로 처리할 수 없을까요? 물론 이 코드도 불편하기는 마찬가지네요.ㅠㅠ

2023-09-03 09:50 UTC, hyemdooly requested changes
comment로 리뷰를 남겨서 Request changes로 다시 남깁니다!
다음부터는 Request changes or Approve로 리뷰 드릴게요🥲

2023-09-04 04:16 UTC, DYGames commented on app/src/main/java/woowacourse/shopping/data/DefaultCartRepository.kt
> +class DefaultCartRepository(private val cartProducts: MutableList<Product> = mutableListOf()) :
헐 생각 못했네요

```kotlin
class DefaultCartRepository(cartProducts: List<Product> = emptyList()) :
    CartRepository {
    private val cartProducts: MutableList<Product> = cartProducts.toMutableList()
```

이렇게 수정했습니다.

2023-09-04 04:45 UTC, DYGames commented on app/src/main/java/woowacourse/shopping/di/Dependencies.kt
> +interface Dependencies
사실 테스트 하기 위함인데요.
Dependencies를 구현하는 객체가 전역적인 의존을 결정하고
이를 DI에서 가변적으로 결정할 수 있도록 하려고 이렇게했습니다.

'어디까지 추상화를 해야하나'는 코드 중복이 일어나는 순간부터 해야한다고 생각하는데용
설계 단계에서 미리 중복이 일어남을 예측하고 추상화로 방지할 수도 있죠.
그렇다고 선제적으로 과도한 추상화는 할 필요 없다고 생각합니다.

2023-09-04 06:06 UTC, DYGames commented on app/src/main/java/woowacourse/shopping/di/DependencyInjector.kt
> +            if (type.isSubtypeOf(it.returnType) || type.isSupertypeOf(it.returnType)) {
type이 인터페이스인 경우를 위한 코드인데 isSubtypeOf() 은 필요 없는 코드인것 같아서 삭제했습니다.

2023-09-04 06:21 UTC, DYGames commented on app/src/main/java/woowacourse/shopping/di/DependencyInjector.kt
> +        dependencies::class.declaredMemberProperties.forEach {
dependencies가 초기화되지 않았으면 이미 예외상황이므로 정상적인 로직 진행이 불가합니다.
초기화 되지 않았을때 직접 예외를 던지는 것도 좋을 것 같습니다.

2023-09-04 06:25 UTC, DYGames commented on app/src/main/java/woowacourse/shopping/di/DependencyInjector.kt
> +    fun inject(type: KType): Any {
get~()은 객체의 상태 값을 반환하는 함수로 생각됩니다.
inject()는 DependencyInjector 클래스의 상태를 반환하는 함수라고 보긴 어려워서 의존성을 주입한다는 의미를 가지는 동사인 inject를 함수명으로 두었습니다.

2023-09-04 06:26 UTC, DYGames commented on app/src/test/java/woowacourse/shopping/data/CartRepositoryTest.kt
> +    fun 장바구니에_존재하지_않는_상품을_존재하면_IndexOutOfBoundsException_예외가_발생한다() {
헐~ 수정했어요

2023-09-04 06:27 UTC, DYGames commented on app/src/test/java/woowacourse/shopping/di/DependencyInjectorTest.kt
> +    )
사실 테스트 클래스끼리 서로 참조할 일 없어서 의미 없는 한정자긴 합니다. 삭제하는게 나을것 같네요!

2023-09-04 06:32 UTC, DYGames commented on app/src/main/java/woowacourse/shopping/ui/ViewModelDependencyInjector.kt
> +    inline fun <reified T : ViewModel> injectViewModel(): ViewModelProvider.Factory =
get~()은 객체의 상태 값을 반환하는 네이밍이라 생각합니다.
ViewModelFactory를 반환하는 함수이니 injectedViewModelFactory가 적절할까요? 여긴 어렵네요 ㅠ

2023-09-04 06:34 UTC, DYGames commented on app/src/test/java/woowacourse/shopping/di/DependencyInjectorTest.kt
> +    fun `Singleton에 TestRepository만 존재하면 TestViewModel 생성에 실패한다`() {
일단 다른 함수도 그렇고 `Singleton에`는 삭제하는게 나을 것 같네용
그리고 `설정한 의존에`로 바꿀 것 같습니다.

`의존이 모두 존재하지 않으면~`은 몹시 좋네요!

2023-09-04 06:40 UTC, DYGames commented on app/src/main/java/woowacourse/shopping/di/DependencyInjector.kt
> +    lateinit var dependencies: Dependencies
inject()를 전역에서 쓰기 위해서 `DependencyInjector`를 object로 둔 거여서 `DependencyInjector`의 인스턴스를 따로 생성할 필요는 없어도 된다고 생각합니다. (inject()를 전역 함수로 뺄 수도 있을 것 같아요)

함수에서 dependencies를 받는 함수도 setDependencies() 이렇게 될 것 같은데 코틀린의 클래스 멤버는 이미 프로퍼티이므로 불필요하다고 생각합니당

사실 미션 2단계 이후로 진행하면서 자연스럽게 해결될 수 도 있는 문제인것 같아요!

고민해주셔서 정말 감사합니다 ㅎ_ㅎ

2023-09-04 06:40 UTC, DYGames commented
둘리 깊게 고민해주시고 코드도 첨부해주셔서 많은 도움이 됐습니다. 저도 이렇게 리뷰 할 수 있을지 모르겠네요 ㅋㅋㅋ 일단 말씀해주신 부분 수정해서 올렸습니다!

감사합니다!

2023-09-04 07:08 UTC, hyemdooly approved these changes
안녕하세요. 코건!
다른 부분은 다 해결이 되었는데 ViewModelFactory를 리턴하는 함수 네이밍이 참 애매한 것 같아요~🤔
저도 오늘 캠퍼스와서 크루들과 네이밍 얘기를 많이 했는데 정답은 없는 것 같습니다.
앞으로 미션하면서 계속 고민해볼 시간이 있을 것 같아서 우선 merge하겠습니다!

2023-09-04 07:08 UTC, hyemdooly commented on app/src/main/java/woowacourse/shopping/ui/ViewModelDependencyInjector.kt
> +    inline fun <reified T : ViewModel> injectViewModel(): ViewModelProvider.Factory =
오 그렇게 생각할 수도 있겠네요!
`injectedViewModelFactory`라... 뭔가 애매하네요🤔

2023-09-04 07:08 UTC, hyemdooly commented on app/src/main/java/woowacourse/shopping/di/DependencyInjector.kt
> +    fun inject(type: KType): Any {
이 부분에 대해 다른 크루들과도 이야기해봤는데 inject로 많이 사용하는 것 같더라구요! 다른 라이브러리에서도 inject라고 많이 명명하는 것 같아요~
그대로 두어도 될 것 같습니다.ㅎㅎ

2023-09-04 07:08 UTC, merged