[아크] 2, 3단계 자동 DI 미션 제출합니다.
woowacourse/android-di pull request #32
Opened 2023-09-10 12:33 UTC by re4rk

안녕하세요 코비! 이번 단계도 잘 부탁드립니다!

3단계 요구 사항 같은 경우 DSL의 구조는 주입 시점이 제가 구상한 것과 방향성이 다르기 때문에 구현하지 않고 넘어갑니다!
추가로 라이브러리 출시 같은 경우는 CodeGen으로 진행하고 따로 개인미션에서 진행하고자합니다!

구현 내용을 설명해드리자면

### Di Container 생명주기
`ApplicationModule`과 `ActivityModule` 총 2개의 모듈 구조가 있는데 이는 모두 각 객체의 생명주기를 따라가게 됩니다!
또한 의존성을 탐색할 때에도 Activity에서 먼저 탐색하고 Application으로 올라가서 탐색하게 됩니다!
만약에 필요한 의존성을 찾게 되면 함수의 로직을 이용해서 객체를 생성하게 됩니다!

### 여러 객체 생성
함수 형식으로 제공하게 된다면 별도로 저장하지 않는 이상 호출 할 떄마다 재 생성 될 것입니다!
객체가 여러번 생성된 것을 막기 위해서 `InstanceHolder`와 `Cache`라는 개념을 도입하게 되었습니다!
InstanceHolder로 Wrapping하고 Cached이라는 object에 보관하도록하였습니다!

### 재귀 의존성
객체 생성을 위한 의존성이 또 필요하게 된다면 현재 `DiContainer`에서부터 계속 의존성에 해당하는 객체를 찾게됩니다!
이를 재귀로 구현하여 의존성들을 구현하고 의존성을 선언하고 필요한 의존성을 함수형식으로 작성하면 자동으로 주입되게 완성시켰습니다!

### HasContainer
DiApplication과 DiActivity와 같이 별도로 객체를 Wrapping하는 것이 아닌 HasContainer의 인터페이스를 활용해서 코드 내부에서 Inject하도록 강제하는 방향으로 진행했습니다!

마지막으로 이번 미션도 TDD로 진행하였습니다! 감사합니다!

### 2단계 필수 요구사항
- [x] ViewModel 내 필드 주입을 구현한다.
- [x] 의존성 주입이 필요한 필드와 그렇지 않은 필드를 구분할 수 없다.
  - [x] Annotation을 붙여서 필요한 요소에만 의존성을 주입한다.
  - [x] 내가 만든 의존성 라이브러리가 제대로 작동하는지 테스트 코드를 작성한다.
- [x] CartRepository가 다음과 같이 DAO 객체를 참조하도록 변경한다.
- [x] CartProductViewHolder의 bind 함수에 다음 구문을 추가하여 뷰에서도 날짜 정보를 확인할 수 있도록 한다.

### 2단계 선택 요구사항
- [x] 현재는 장바구니 아이템 삭제 버튼을 누르면 RecyclerView의 position에 해당하는 상품이 지워진다.
  - [x] 상품의 position과 CartRepository::deleteCartProduct의 id가 동일한 값임을 보장할 수 없다는 문제를 해결한다.
  - [x] 뷰에서 CartProductEntity를 직접 참조하지 않는다.

### 3단계 필수 요구사항
- [x] 하나의 인터페이스의 여러 구현체가 DI 컨테이너에 등록된 경우, 어떤 의존성을 가져와야 할지 알 수 없다.
  - [x] 상황에 따라 개발자가 Room DB 의존성을 주입받을지, In-Memory 의존성을 주입받을지 선택할 수 있다.
- [x] 내가 만든 DI 라이브러리를 모듈로 분리한다.

### 3단계 선택 요구사항
- [ ] DSL을 활용한다.
- [ ] 내가 만든 DI 라이브러리를 배포하고 적용한다.

2023-09-11 15:19 UTC, woowahan-leah requested changes
안녕하세요 아크!
TDD로 구현하신 만큼 DI 라이브러리를 사용하면서 생길 수 있는 다양한 시나리오를 고려한 것 같아 매우 인상적이에요. 개선 제안 피드백이 있긴 하지만 지금 구조로도 다음 단계를 구현하시는데에는 무리가 없을 듯 합니다.
제가 드린 코멘트는 참고만 해주시고 리뷰어인 코비의 가이드를 따라가주시면 됩니다.

2023-09-11 15:19 UTC, woowahan-leah commented on ark_di/src/test/java/com.re4rk.arkdi/DiContainerTest.kt
> +class DiContainerTest {
필드 주입에 대한 테스트 케이스가 누락되었습니다.
필드 주입과 Qualifier를 함께 활용하는 경우도 검증하면 어떨까요?

2023-09-12 23:17 UTC, re4rk commented on app/build.gradle.kts
> +    kapt(project(":ark_di"))
Code-Gen을 하다가 넘어와서 무의식적으로 작성한 것같습니다! 바로 제거하였습니다! [b829b12](https://github.com/woowacourse/android-di/pull/32/commits/b829b121ed944a17a2123308db6301b8a996d01d)

2023-09-12 23:17 UTC, re4rk commented on app/src/main/java/woowacourse/shopping/di/DiActivityModule.kt
> +    }
보일러 플레이트가 심해지는 것은 인식했지만 괜찮겠지 하고 넘어갔었는데 이번에 Map방식으로 변경하였습니다! [8d8ac5e](https://github.com/woowacourse/android-di/pull/32/commits/8d8ac5ee590c3237327984d0ea85c1d0c8b0b582)

2023-09-12 23:19 UTC, re4rk commented on ark_di/src/main/java/com/re4rk/arkdi/Qualifier.kt
> +annotation class Qualifier(val value: String)
좋은 방법은 알지만 괜찮나..? 의아하면서 도입했었는데 주관이 들어간 방식으로 변경하였습니다! [866498a](https://github.com/woowacourse/android-di/pull/32/commits/866498ad769e8c77ca543080e3ff30984a5babd2)

2023-09-12 23:23 UTC, re4rk commented on app/src/main/java/woowacourse/shopping/data/CartInMemoryRepository.kt
> +) : CartRepository {
이런 실수를 하다니 부끄럽습니다 ㅠㅠㅠ 반영했습니다! [5789cd9](https://github.com/woowacourse/android-di/pull/32/commits/5789cd9f74402128a6b60397513ccac5d261195b)

2023-09-12 23:32 UTC, re4rk commented on ark_di/src/test/java/com.re4rk.arkdi/DiContainerTest.kt
> +class DiContainerTest {
해당 테스트케이스를 만들어보니 통과가 되지 않아서 바로 수정했습니다 ㅠㅠ [23647c5](https://github.com/woowacourse/android-di/pull/32/commits/23647c5b9929e0fec28a2a805e1a217b27d22d82)

2023-09-12 23:48 UTC, re4rk commented on app/src/main/java/woowacourse/shopping/ui/cart/CartActivity.kt
> +
Base Activity 등의 문제점들을 해결하기 위해서 위의 보일러 플레이트와 HasContainer와 함께 이를 해결하려고 여러 방식을 사용해 보았으나 기존 방식대로 롤백하였습니다! [2fa5991](https://github.com/woowacourse/android-di/pull/32/commits/2fa59912b244973535844797d70196f2cd3f1572)

2023-09-12 23:51 UTC, re4rk commented on app/src/main/java/woowacourse/shopping/AppApplication.kt
> +class AppApplication : Application(), HasDiContainer {
`ComponentActivity` 구조에서  `HasDefaultViewModelProviderFactory`의 영감을 받아서 코드를 작성했었습니다!
`Has~` 인터페이스 명을 통해서 무슨 역할을 가지고 있는지 파악이 쉽다고 생각하여 반영을 하였었습니다!
현재에는 프로젝트 구조를 변경하여 사라졌습니다! [2fa5991](https://github.com/woowacourse/android-di/pull/32/commits/2fa59912b244973535844797d70196f2cd3f1572)
``` java
public class ComponentActivity extends androidx.core.app.ComponentActivity implements
        ContextAware,
        LifecycleOwner,
        ViewModelStoreOwner,
        HasDefaultViewModelProviderFactory,
        SavedStateRegistryOwner,
        OnBackPressedDispatcherOwner,
        ActivityResultRegistryOwner,
        ActivityResultCaller,
        OnConfigurationChangedProvider,
        OnTrimMemoryProvider,
        OnNewIntentProvider,
        OnMultiWindowModeChangedProvider,
        OnPictureInPictureModeChangedProvider,
        MenuHost {
```

2023-09-13 04:38 UTC, chws0508 commented on app/src/main/java/woowacourse/shopping/di/DiActivityModule.kt
> +    }
모듈을 생성하는 과정에서, Application 을 직접 꺼내서 사용하기 때문에 서비스 로케이터 패턴일까요?

2023-09-13 16:40 UTC, rhkrwngud445 requested changes
리뷰가 늦었네요 아크! 테스트 코드를 꼼꼼하게 짜두어서, 기능을 이해하는데 도움이 되었습니다!
절대 레아의 식탁에 숟가락을 올리는게 아니라.. 잘 구현해주셔서 리뷰할게 안보이네요!
조그만 제안들을 드렸는데 확인 부탁합니다~! (코멘트로 의견 주셔도 좋습니다)

2023-09-14 02:28 UTC, re4rk commented on ark-di/src/main/java/com/re4rk/arkdi/DiContainer.kt
> +    private fun getInstance(kType: KType, qualifier: Annotation?): Any? {
저도 처음에는 오버로딩을 지양하려고 생각했습니다!
제가 오버로딩을 선택한 이유는 3개의 메소드가 모두 같은 기능을 수행하고 있기 때문입니다!
같은 기능을 수행하고 있기 때문에 네이밍에서 분기를 하여 명확하게 표현을 하기 위해서는 파라미터의 정보를 나타낼수 밖에 없다고 생각이들고 있습니다! 만약에 3개의 메소드가 각자의 역할을 나타낸다고 치면
``` kotlin
fun getInstance(clazz: KClass<T>)
fun getArgument(kParameter: KParameter)
fun getOrCreateInstance(kType: KTpe, qualifier: Annotation?)
```
와 같이 네이밍을 예상할 수 있다고 생각합니다!

하지만 오히려 이는 메소드끼리의 구분은 될지는 몰라도 클래스 전체적인 복잡도는 더욱 증가한다고 보고 있습니다!
예시로 기능 추가가 된다고 가정을 한다면 IDE 기능을 통해서 getInstance만 검색하고 가지고 있는 인자들을 활용할 수 있는지 확인 할 수 있지만 만약에 메소드 끼리의 분리를 위해서 사용한다면 클래스 내부 메소드들을 모두 탐색해야하는 경우가 생긴다고 생각합니다!

핵심 메소드는 가장 아래인 `getInstance(kType: KType, qualifier: Annotation?)`이고 나머지 두 메소드는 인자를 적절히 분배해주는 역할만 가지고 있는 것이 저는 생성자와 같다고도 생각하고 있습니다!
 `getInstance(kType: KType, qualifier: Annotation?)`는 primary constructor이고 나머지 두 메소드는 secondary constructor라는 관점으로 바라보았기 때문입니다!

2023-09-14 02:36 UTC, re4rk commented on app/src/main/java/woowacourse/shopping/di/ContextType.kt
> +}
말씀해주신대로 해당 어노테이션들은 기본으로 제공해도 괜찮다고 생각이 들어서 ark-di 모듈로 이동시켰습니다! [b62a52e](https://github.com/woowacourse/android-di/pull/32/commits/b62a52e6da29fd1c0cb5481ca7b360d298d61849)

2023-09-14 07:39 UTC, merged

2023-09-14 07:40 UTC, rhkrwngud445 commented
많이 배워갑니다 아크~! 다음 스텝도 화이팅~!