[로피] 2, 3단계 자동 DI 미션 제출합니다
woowacourse/android-di pull request #37
Opened 2023-09-13 04:51 UTC by Choisehyeon

안녕하세요 글로😄
2차 필수& 선택, 3차 필수 요구사항을 구현했습니다!
3차 선택 요구사항은 추후 반영해보도록 하겠습니다😂
리뷰 잘 부탁드려용😊

## 2단계 요구사항
### 필수
- [x] ViewModel 내 필드 주입을 구현한다..
- [x] 의존성 주입이 필요한 필드와 그렇지 않은 필드를 구분할 수 없다.
  - [x] Annotation을 붙여서 필요한 요소에만 의존성을 주입한다.
  - [x] 내가 만든 의존성 라이브러리가 제대로 작동하는지 테스트 코드를 작성한다.
- [x] CartRepository가 다음과 같이 DAO 객체를 참조하도록 변경한다.
- [x] CartProductViewHolder의 bind 함수에 다음 구문을 추가하여 뷰에서도 날짜 정보를 확인할 수 있도록 한다.

### 선택
- [x] 현재는 장바구니 아이템 삭제 버튼을 누르면 RecyclerView의 position에 해당하는 상품이 지워진다.
  - [x] 상품의 position과 CartRepository::deleteCartProduct의 id가 동일한 값임을 보장할 수 없다는 문제를 해결한다.
- [x] 뷰에서 CartProductEntity를 직접 참조하지 않는다.

## 3단계 요구사항
### 필수
- [x] 하나의 인터페이스의 여러 구현체가 DI 컨테이너에 등록된 경우, 어떤 의존성을 가져와야 할지 알 수 없다.
  - [x] 상황에 따라 개발자가 Room DB 의존성을 주입받을지, In-Memory 의존성을 주입받을지 선택할 수 있다.
- [x] 내가 만든 DI 라이브러리를 모듈로 분리한다.

### 선택
- [ ] DSL을 활용한다.
- [ ] 내가 만든 DI 라이브러리를 배포하고 적용한다.

2023-09-14 08:24 UTC, ippnsj requested changes
안녕하세요 로피 🥰
자동 주입을 구현하면서 여러 고민을 했다는게 느껴지네요! 👏
제가 미처 생각하지 못한 방법도 있어서 덕분에 다른 방법도 생각해볼 수 있게 되었어요! 
이번 미션도 수고 많았습니다~! 🥳

2023-09-14 08:24 UTC, ippnsj commented on di/src/test/kotlin/woowacourse/shopping/di/inject/CustomInjectorTest.kt
> +        assertEquals(viewModel.datas, datas)
gradle에 보니까 assertj를 추가하셨더라고요!
assertThat을 사용하지 않은 이유가 있을까요?

2023-09-14 08:24 UTC, ippnsj commented on di/src/test/kotlin/woowacourse/shopping/di/inject/CustomInjectorTest.kt
> +        assertEquals(viewModel.cartRepository.javaClass.kotlin, FakeInMemoryCartRepository::class)
assertThat을 사용하면 isInstanceOf라는 함수도 유용하답니다~

2023-09-14 08:24 UTC, ippnsj commented on di/src/test/kotlin/woowacourse/shopping/di/inject/CustomInjectorTest.kt
> +    fun `DependencyContainer에서 instance가 없다면 생성하여 주입한다`() {
테스트 제목으로는 어떤 instance가 존재하지 않는지 알 수 없을 것 같아요~!
then에서도 instance가 존재하지 않는 클래스의 인스턴스가 생성되었는지를 확인하는게 아니라서 테스트 코드만 보아서는 위 테스트와 다른점을 잘 모를 수 있을 것 같아요!

2023-09-14 08:30 UTC, ippnsj reviewed
👍 👍 👍

2023-09-15 05:17 UTC, Choisehyeon commented on app/src/main/java/woowacourse/shopping/ShoppingApplication.kt
> +        )
필요한 인스턴스가 많아지면 onCreate에서 하는 일이 많아질 것 같네요!! 글로 의견처럼 필요한 시점에 생성하는게 좋을 것 같아요! 감사합니다😍

2023-09-15 05:38 UTC, Choisehyeon commented on app/src/main/java/woowacourse/shopping/data/InMemoryCartRepository.kt
> +        cartProducts.removeAt(id.toInt())
InMemory도 DatabaseCartRepository 처럼 id를 통해서 상품을 삭제할 수 있도록 수정했습니다😄

2023-09-15 06:05 UTC, Choisehyeon commented on app/src/test/java/woowacourse/shopping/main/MainViewModelTest.kt
> +            }
이렇게 테스트하는 방법이 많았네요!!! 이번 step2,3는 제가 한 방식으로 진행한 후 step4때 더 편한다고 생각하는 걸로 변경해보겠습니다!! 감사해용😍

2023-09-15 06:06 UTC, Choisehyeon commented on di/src/main/java/woowacourse/shopping/di/container/DependencyContainer.kt
> +            )
오오 이렇게 하면 되는군요!!! 👍

2023-09-15 06:19 UTC, Choisehyeon commented on di/src/main/java/woowacourse/shopping/di/container/DependencyContainer.kt
> +        val annotationWithQualifier = instance::class.annotations.filter {
여러 개의 Qualifier가 들어갈 수 있다고 생각을 해서 이렇게 했었는데 단일 Annotation으로 하는게 맞는 것 같아요!!!

2023-09-15 06:20 UTC, Choisehyeon commented on di/src/test/kotlin/woowacourse/shopping/di/inject/CustomInjectorTest.kt
> +        assertEquals(viewModel.datas, datas)
하하 사실 사용하지 않은 이유가 따로 있는 건 아니었어요😂
모듈을 만들 때 assertj가 기본적으로 되어 있어서 그냥 사용했었습니다😁

2023-09-15 06:22 UTC, Choisehyeon commented on di/src/test/kotlin/woowacourse/shopping/di/inject/CustomInjectorTest.kt
> +        assertEquals(viewModel.cartRepository.javaClass.kotlin, FakeInMemoryCartRepository::class)
감사합니다😄 assertThat을 사용해도 유용할 것 같네요!! assertThat은 step4에서 적용해보도록 하겠습니다!!

2023-09-15 06:47 UTC, Choisehyeon commented on di/src/main/java/woowacourse/shopping/di/container/DependencyContainer.kt
> +        val annotationWithQualifier = instance::class.annotations.filter {
annotation으로 구현을 하면서 어떤 것을 주입해야할지 명확하게 알 수 있다는 점이 좋았는데 
글로 의견처럼 annotation 클래스의 개수가 많아질수도 있겠네요! 
흠 저는 사실 이번 미션에서는 구현체가 많지는 않아서 이렇게 진행했을 때 어떤 구현체를 사용해야할지 명확하게 알 수 있다는 장점이 더 컸는데요. 
구현체가 많아지게 되면 필요한 경우에만 annotation 클래스를 구현하고 중복되는 annotation 클래스는 제거하거나 합치는 것도 괜찮은 것 같아요! 그리고 비슷한 목적을 가진 annotation 같은 경우에는 그룹화를 해서 어노테이션을 관리할 수도 있을 것 같아요😄

2023-09-15 13:15 UTC, Choisehyeon commented
안녕하세요 글로😄 
2,3 단계 미션 피드백을 거의 다 반영하였는데요! 반영하지 못한 부분은 4단계 진행하면서 구조를 개선해야할 부분이 생길 것 같은데 그 때 같이 반영해보려고 합니다! 아직 어떻게 의존성을 관리하고 주입해야할지 구조를 계속 고민 중인 상태라서 많은 시간이 걸릴 것 같아 2,3 단계는 구조 변경을 크게 하지 않고 피드백 위주로 반영했어요😊

2023-09-16 04:59 UTC, ippnsj approved these changes
수고많았어요 로피! 🥰
리뷰하면서 함께 생각해볼 수 있어서 좋았어요! 
다음 단계에서도 함께 고민해보아요~ 😊
화이팅!!! 💪

2023-09-16 05:00 UTC, merged

2023-09-16 14:31 UTC, ippnsj commented on app/src/main/java/woowacourse/shopping/data/InMemoryCartRepository.kt
> +    )
아! 사실 실제 서비스에서 사용할 수 있는 구현체에는 미리 카트 상품을 담아두면 사용자가 자신이 담지 않은 상품이 담겨 있어 당황스러울 수 있다는 말이었는데 상품명을 바꾸셨군요!ㅋㅋㅋㅋ😂