[토마스] 2, 3단계 자동 DI 미션 제출합니다
woowacourse/android-di pull request #51
Opened 2023-09-13 08:59 UTC by ki960213

2023-09-14 06:04 UTC, pingu244 requested changes
토마스 안녕하세요~!
2, 3 단계 미션 고생 많으셨습니다.
코드양에서부터 토마스의 열정이 잘 느껴졌습니다ㅋㅋㅋ
제가 모든 코드를 완벽하게 이해하고 리뷰를 남겨드릴 수는 없을 것 같아 전체적인 흐름만 파악한 상태에서 미션 요구사항 중심으로 살펴보았는데요, 구현을 잘해주셔서 리뷰 드릴 부분이 딱히 보이지 않았습니다.
도움이 될 리뷰를 남기지 못해 미안하네요😂
오히려 제가 토마스의 꼼꼼한 테스트를 보고 많이 배워갑니다!👍
+) 토마스에게 더 도움이 될 수 있게 레아께 토마스의 코드리뷰를 요청드렸습니다! 조금 기다려주시면 레아가 리뷰 주실겁니다!

2023-09-14 06:13 UTC, ki960213 commented on domain/src/main/java/woowacourse/shopping/model/Product.kt
> +    val createdAt: Long,
생각해보니 상품과 장바구니에 담긴 상품은 다른 모델로 만들어야 할 것 같네요! 감사합니다

2023-09-14 06:15 UTC, ki960213 commented on sheath/src/main/java/com/ki960213/sheath/SheathApplication.kt
> +            scanner.findAll() + SheathComponentByContext(context)
Hilt는 `@ApplicationContext`로 ApplicationContext를 주입하더라구요! 그리고 Database를 만들 때 Context가 필요한 것을 보고 Context 자동 주입 기능도 필요하다고 생각해서 DI 프레임워크 실행할 때 받은 Context를 의존성 관리 대상으로 등록하기 위해 만들었습니다!

2023-09-14 06:15 UTC, ki960213 commented on sheath/src/test/java/com/ki960213/sheath/component/SheathComponentByFunctionTest.kt
같은 검증 기능끼리 묶어놨다면 더 보기 좋았을텐데 좋게 봐주셔서 감사합니다!

2023-09-14 06:28 UTC, ki960213 commented on sheath/src/main/java/com/ki960213/sheath/scanner/DefaultComponentScanner.kt
> +        return components
안드로이드가 실행되기 위해서는 Dex 파일로 변환되어야 합니다. 변환된 Dex 파일을 탐색해서 특정 클래스를 찾는 것 같아요! 
`PathClassLoader`는 저도 잘 몰라서 chatGPT의 답변을 드리겠습니다.
> `PathClassLoader`는 안드로이드에서 사용되는 클래스 로더 중 하나입니다. 클래스 로더는 클래스 파일을 로드하고 클래스를 인스턴스화하는 데 사용됩니다. `PathClassLoader`는 특정 디렉터리 경로나 JAR 파일에 있는 클래스를 로드하는 데 사용되는 클래스 로더입니다.
주로 안드로이드 애플리케이션의 클래스 로딩 작업을 처리하는 데 사용됩니다. 각 애플리케이션은 독립된 클래스 로더를 가지며, PathClassLoader는 애플리케이션의 클래스 경로에 있는 클래스 파일을 로드합니다.
안드로이드에서는 애플리케이션 컴포넌트(액티비티, 서비스, 브로드캐스트 리시버 등)가 실행될 때 해당 애플리케이션의 클래스 로더가 생성되고 사용됩니다. `PathClassLoader`는 이런 클래스 로더 중 하나로, 애플리케이션의 클래스 파일을 찾고 로드하는 역할을 합니다.
간단히 말해, `PathClassLoader`는 특정 디렉터리나 JAR 파일에 있는 클래스를 로드하기 위한 도구로 사용되며, 안드로이드 애플리케이션의 클래스 로딩 메커니즘 중 하나입니다.

클래스로더를 이용해서 Dex파일에서 찾은 클래스 이름을 이용해 클래스를 로드하고, 로딩된 클래스가 찾길 원하는 클래스인지 검사 후 찾길 원하는 클래스라면 SheathComponent로 추가하는 로직이라고 생각합니다! 사실 이 코드는 저도 stackoverflow에서 찾은 걸 일부 변경해서 정확히는 잘 모르겠습니다... 😓

2023-09-14 06:31 UTC, ki960213 commented on sheath/src/main/java/com/ki960213/sheath/scanner/DefaultComponentScanner.kt
> +        val classNames = dexFile.entries()
처음엔 [Reflections 라이브러리](https://www.baeldung.com/reflections-library)를 이용해 특정 패키지 하위에 있는 특정 애노테이션이 붙은 클래스를 찾으려고 했는데, 안드로이드에서는 이 라이브러리가 제대로 동작하지 않았습니다. 그래서 어쩔 수 없이 다른 방법을 찾다가 stackoverflow에서 찾은 코드를 이용해서 스캔하도록 했습니다 😢

2023-09-14 08:11 UTC, woowahan-leah requested changes
안녕하세요 토마스!
토마스가 작성하신 라이브러리 구조를 흥미롭게 잘 봤습니다 :)
자세한 구현에 대한 피드백보다는, 전체적인 구조에 대한 피드백을 남겼으니 참고해주시면 감사하겠습니다.
제 의견은 참고만 해주시고 핑구의 가이드에 맞춰 미션을 마무리해주시면 됩니다~

2023-09-14 08:11 UTC, woowahan-leah commented on sheath/src/main/java/com/ki960213/sheath/SheathApplication.kt
> +        val scanner = DefaultComponentScanner(context)
토마스가 작성하신 DI 구조 흥미롭게 잘 봤습니다 👍 

다른 크루들은 대부분 개발자가 의존성 주입이 필요한 컴포넌트를 직접 정의하고 해당 컴포넌트 주입 코드를 따로 관리하는 식의 구조를 구상했었는데요, 토마스가 작성하신 구조는 리플랙션의 이점을 누릴 수 있는 구조로 보입니다. 여담이지만 웹 백엔드 레벨4 미션 중 JPA DI Container 구현 미션이 있는데요, 해당 미션에서 토마스와 비슷한 구조로 설계한 크루들을 많이 볼 수 있습니다.

**아래부터는 참고만 해주세요. 꼭 미션에 반영하진 않으셔도 되나, 이런 문제가 있을 수 있다는 사실만 인지하셔도 좋습니다.**

웹 서버와 안드로이드 어플리케이션의 가장 큰 차이 중 하나는 부팅 시 속도가 얼마나 사용자 경험에 영향을 주는지입니다. 웹 서버의 경우 서버가 띄워지고 특별히 다시 shutdown될 일이 없다면 계속 유지되지만, 안드로이드 어플리케이션은 디바이스 메모리 제약으로 인해 하루에도 수십번씩 껐다 켜질 수 있습니다.

이때 앱 실행시마다 리플랙션을 통해 클래스 정보를 알아오고 동적으로 메모리에 로딩하는 과정을 거치게 되면 로딩 성능에 악영향을 줄 수 있습니다. 앱이 커질수록 심해집니다. 

때로는 모바일 환경에서는 Hilt, Koin처럼 개발자가 직접 주입이 필요한 의존성을 선언해두고 별도의 스캔 절차를 거치지 않는 것이 성능상 이점을 가져갈 수 있다는 의미입니다. 두 구조 중 어떤 것이 더 낫다는 이야기보다는 상황에 맞게 적절하게 선택하는 것도 좋을 것 같습니다.

단, KSP나 Kapt 활용을 의도한건 아닙니다. 우리는 레벨4 DI 미션을 통해 바퀴를 더 잘 이해할 수 있도록 바퀴를 직접 만들어보고 있습니다. 이 과정에서 완벽한 DI 라이브러리를 만들기보다는 학습을 위한 수단으로 활용하기 위해, KSP나 KAPT가 아닌 리플랙션을 활용하고 있습니다. 만약 토마스가 느끼시기에 지금 구조를 작성하며 바퀴를 더 잘 이해했다고 생각하신다면 이대로도 충분합니다.

2023-09-14 08:11 UTC, woowahan-leah commented on sheath/src/main/java/com/ki960213/sheath/scanner/DefaultComponentScanner.kt
> +        val dexFile = DexFile(context.packageCodePath)
왜 DexFile 클래스가 Deprecated되었는지 이해하기 위해서는 아래 공식 문서와 안드로이드 런타임에 대한 배경지식이 필요할 수 있습니다.
- https://source.android.com/docs/core/runtime
- https://brunch.co.kr/@mystoryg/81
- https://brunch.co.kr/@mystoryg/82

2023-09-14 08:11 UTC, woowahan-leah commented on sheath/src/test/java/com/ki960213/sheath/component/SheathComponentByClassTest.kt
테스트 코드를 정말 신경써서 작성해주셨군요!

테스트 코드가 일종의 문서 역할도 할 수 있다는 사실을 잘 이해하고 계신 것 같아요. 
그리고 이렇게 다른 개발자에게 내가 작성한 코드의 동작 원리를 이해할 수 있도록 설명하는 예시를 참고해보시면 좋을 것 같아 Dagger 라이브러리의 링크를 남깁니다. 때로는 아주 구체적인 단위의 테스트가 아니라 작성한 기능에 대한 시나리오를 명시적으로 확인할 수 있는 테스트가 한눈에 더 잘 이해할 수 있게 만들어주기도 합니다. 
- https://github.com/google/dagger/blob/master/javatests/dagger/android/AndroidInjectionTest.java
- https://github.com/google/dagger/tree/master/examples/bazel/java/example/hilt

참고:
https://github.com/woowacourse/android-di/pull/29#discussion_r1321575419

2023-09-14 11:25 UTC, ki960213 commented on app/src/main/java/woowacourse/shopping/data/DatabaseCartRepository.kt
> +annotation class DatabaseCart
종속 항목 주입 대상을 클래스로 한정지을 수 있도록 한다면 종속 항목을 사용하는 클래스에만 한정자를 설정해도 원하는 구체 클래스의 인스턴스를 주입받을 수 있군요! 감사합니다 😊 
위와 관련되어 궁금한 점이 있습니다. 제가 만든 라이브러리는 구체 클래스에 특정 애노테이션을 붙여서 의존성 관리 대상으로 만들 수 있습니다.(함수로 의존성 관리 대상을 등록한다면 구체 클래스의 코드는 바뀌지 않습니다.) 만약 다른 DI 라이브러리로 교체하려면 모든 구체 클래스에 설정된 애노테이션을 제거해야 합니다. 그래도 저라면 애노테이션 방식으로 의존성 관리할 수 있다면 DI 라이브러리 교체 가능성을 배제하고 사용할 것 같습니다. 애노테이션 방식이 더 편하다고 생각하기 때문입니다. 레아는 어떻게 생각하시나요? ❓

2023-09-14 12:21 UTC, ki960213 commented on sheath/src/main/java/com/ki960213/sheath/SheathApplication.kt
> +        val scanner = DefaultComponentScanner(context)
사실 저는 이번 미션을 진행하면서 어떻게 하면 더 편리하게 개발자가 의존성을 관리할 수 있을까 생각하며 미션을 수행했습니다. hilt의 사용법을 보고 더 편하게 사용할 수 있도록 개선하는 것을 고민했을 뿐, hilt의 내부 원리는 크게 고민하지 않았습니다. 라이프 사이클 관련 기능을 구현하기 위해 hilt를 참고하여 hilt의 이해도를 올리는 데 집중하겠습니다! 😄 
레아의 피드백을 받고 궁금한 점이 생겼습니다. 저도 처음에 모든 패키지를 탐색 후 리플렉션으로 의존성을 파악 후 주입해주는 과정이 패키지의 규모가 커지면 성능 상 문제가 될 수 있다고 생각했습니다. 하지만 저는 "그 정도로 규모가 큰 앱이면 스플래시 화면을 보여주면 되지 않을까?"라고 생각하며 최대한 편하게 의존성을 관리할 수 있는 방법을 고민했습니다. 혹시 스플래시 화면을 보여주더라도 이러한 방식은 문제가 될 수 있나요?

2023-09-15 00:55 UTC, woowahan-leah commented on sheath/src/main/java/com/ki960213/sheath/SheathApplication.kt
> +        val scanner = DefaultComponentScanner(context)
@ki960213 이번 미션의 주제가 완벽한 DI 라이브러리를 만들려고 노력하는 것이기보다, 그 과정에서 학습을 유도하는 것이기에 지금도 충분히 토마스에게는 좋은 경험이 됐을 것이라고 생각해요. 꼭 Hilt와 똑같이 만들지 않아도 됩니다.

질문에 대한 답변을 드리자면 다음 영상이 도움될 수 있을 것 같네요! 토스 앱 오픈시간 1초를 줄이기 위해서 수많은 노력을 하는 개발자의 사례를 참고해보시면 어떨까요?
- https://www.youtube.com/watch?v=IVt7HjUM0LQ

2023-09-15 01:01 UTC, woowahan-leah commented on app/src/main/java/woowacourse/shopping/data/DatabaseCartRepository.kt
> +annotation class DatabaseCart
@ki960213 이건 개발자들마다 의견이 다를 것 같네요! 만약 프로젝트 전체적으로 DI 라이브러리를 사용하고 있고, Repository 인터페이스가 수정되는 것이 아닌 구현체라면 저도 토마스의 의견이 합리적이라고 생각합니다. 물론 나중에 DI 라이브러리 교체할 때 어려움이 있을 수 있고 이 구현체가 DI 라이브러리에 의존하는 상황의 단점을 충분히 이해한다면 개발자가 적절한 방법을 선택해도 될 것 같아요.

2023-09-15 14:48 UTC, ki960213 commented on sheath/src/main/java/com/ki960213/sheath/SheathApplication.kt
> +        val scanner = DefaultComponentScanner(context)
규모가 큰 앱이라면 의존성 컨텍스트를 초기화하는 것 말고도 많은 것들을 초기화해야 할 수도 있군요! 그리고 초기화 하는 로직은 대부분 의존성 컨텍스트가 초기화 되어야만 실행될 수 있으므로 의존성 컨텍스트를 초기화하는 시간이 꽤 치명적일 수 있군요! 감사합니다. 😄

2023-09-17 01:50 UTC, woowahan-leah commented
@ki960213 @pingu244 제가 작성한 코멘트를 모두 반영하는게 필수는 아닙니다! 
핑구가 보시기에 다음단계를 진행하는데에 무리가 없다고 판단되시면 머지해주세요 🙂

2023-09-18 13:53 UTC, pingu244 approved these changes
step4 진행을 위해 바로 머지하겠습니다! 토마스 정말..대단하네요...👍

2023-09-18 13:53 UTC, merged