[글로] 1단계 자동 DI 미션 제출합니다
woowacourse/android-di pull request #6
Opened 2023-09-03 13:56 UTC by ippnsj

안녕하세요! 로피! 🥰
이번 미션 잘 부탁드립니다~
선택 요구 사항을 제외한 모든 요구사항은 만족한 상태입니다!
선택 요구 사항은 추후에 커밋을 추가하고 체크하도록 하겠습니다! 😉

## 구현방법
- 커스텀 ViewModelFactory를 생성하여 레포지토리가 주입된 ViewModel을 반환하도록 했습니다.
- 모든 레포지토리 인스턴스는 AppContainer가 관리하도록 했습니다.
- AppContainer는 ApplicationClass에서 한 번만 생성하여 관리하도록 했습니다.
- AppContainer의 inject 함수에 주입받고자 하는 클래스(현 상황에서는 ViewModel이 유일)를 넘겨주면 생성시 필요한 레포지토리 인스턴스를 찾아 주입해준 후 반환하도록 했습니다.
- 만약 주입받고자 하는 클래스의 주생성자가 존재하지 않거나 주입해야하는 인스턴스가 존재하지 않으면 예외가 발생합니다.

## 요구사항
### 기능 요구 사항
생성자 주입 - 수동
- [x] 테스트하기 어렵다.
- [x] Repository 객체를 교체하기 위해 또다른 객체를 만들어 바꿔줘야 한다. 즉, ViewModel에 직접적인 변경사항이 발생한다.

생성자 주입 - 자동
- [x] ViewModel에서 참조하는 Repository가 정상적으로 주입되지 않는다.
- [x] Repository를 참조하는 다른 객체가 생기면 주입 코드를 매번 만들어줘야 한다.
  - [x] ViewModel에 수동으로 주입되고 있는 의존성들을 자동으로 주입되도록 바꿔본다.
  - [x] 특정 ViewModel에서만이 아닌, 범용적으로 활용될 수 있는 자동 주입 로직을 작성한다. (MainViewModel, CartViewModel 모두 하나의 로직만 참조한다)
  - [x] 100개의 ViewModel이 생긴다고 가정했을 때, 자동 주입 로직 100개가 생기는 것이 아니다. 하나의 자동 주입 로직을 재사용할 수 있어야 한다.
- [x] 장바구니에 접근할 때마다 매번 CartRepository 인스턴스를 새로 만들고 있다.
  - [x] 여러 번 인스턴스화할 필요 없는 객체는 최초 한 번만 인스턴스화한다. (이 단계에서는 너무 깊게 생각하지 말고 싱글 오브젝트로 구현해도 된다.)
 
### 선택 요구 사항
- [ ] TDD로 DI 구현
- [ ] Robolectric으로 기능 테스트
- [ ] ViewModel 테스트
- [ ] 모든 도메인 로직, Repository 단위 테스트

### 프로그래밍 요구 사항
- [x] 사전에 주어진 테스트 코드가 모두 성공해야 한다.
- [x] Annotation은 이 단계에서 활용하지 않는다.

2023-09-04 07:18 UTC, Choisehyeon requested changes
안녕하세요 글로😄
요구사항을 빠른 시간 안에 구현하셨네요👍👍
피드백 드릴 부분이 딱히 생각나지 않아서, 보면서 궁금한 점들 위주로 리뷰 남겼습니다!

2023-09-04 10:44 UTC, ippnsj commented on app/src/main/java/woowacourse/shopping/di/AppContainer.kt
> +    fun <T : Any> inject(clazz: Class<T>): T {
음! 저는 inject라는 함수가 클래스 타입을 받아서 필요한 프로퍼티가 inject된 인스턴스를 반환하는 것도 완전히 어울리지 않다고는 생각하지 않았어요~!
Angular에 정의된 inject 함수도 injected value를 반환하더라구요! 😆
[Angular inject 함수 공식 문서](https://angular.io/api/core/inject)

2023-09-04 11:01 UTC, ippnsj commented on app/src/main/java/woowacourse/shopping/ShoppingApplication.kt
> +}
공식문서를 따라서 코드를 작성하다보니 위와 같이 작성하게 되었는데요! 🤣
[Managing dependencies with a container](https://developer.android.com/training/dependency-injection/manual#dependencies-container)
둘의 가장 큰 차이는 appContainer가 application 인스턴스가 생성되기 전에 생성되냐 아니면 application 인스턴스가 생성된 이후에 생성되냐의 차이인 것 같아요!
appContainer의 경우에는 반드시 application 인스턴스가 생성된 후에 생성해야 할 필요는 없다고 생각해서 위와 같이 작성해도 괜찮지 않을까 생각합니다! 😊

2023-09-04 11:11 UTC, ippnsj commented on app/src/main/java/woowacourse/shopping/di/AppContainer.kt
> +    private val cartRepository = CartRepository()
추상화하지 않은 이유가 따로 있지는 않았습니다!
로피의 리뷰를 보고 생각해보니 테스트를 용이하게 하고 (물론 mock을 하는 방법도 있겠지만 mock에 대한 의견은 분분하니!) 변화에 취약하지 않게 하려면 Repository를 추상화하는 것이 좋을 것 같아요!
반영하도록 하겠습니다~! 감사합니다! 🥰

2023-09-05 06:52 UTC, Choisehyeon commented on app/src/main/java/woowacourse/shopping/ShoppingApplication.kt
> +}
글로 의견처럼 이번 미션에서는 의존성 변경이 필요하지 않기 때문에 appContainer가 application 인스턴스가 생성 된 후에 생성될 필요는 없을 것 같네요!! 나중에 애플리케이션 라이플 사이클 내에서 여러 번 다른 의존성을 주입해야할 때 onCreate 안에서 하면 될 것 같아요😄

2023-09-06 01:18 UTC, Choisehyeon approved these changes
글로😄 1단계 미션하느라 수고많았어요!!
뷰모델 테스트도 추가해주었네요👍 
다음 미션에는 구조에 대해 좀 더 고민해보면서 서로의 의견을 더 나누어 보면 좋을 것 같아요😊😊
이번 미션은 이만 approve하겠습니다!

2023-09-06 01:21 UTC, merged