[하티] 4단계 자동 DI 미션 제출합니다
woowacourse/android-di pull request #62
Opened 2023-09-19 06:54 UTC by sujin9

작성 즁,,

2023-09-20 01:04 UTC, rhthrhrl0 requested changes
안녕하세요 하티 :) 
이번 스텝에서 생명주기를 고려하면서 고민한 흔적이 보여서 좋았고, 전체적으로 구조와 코드가 깔끔해서 리뷰하기 편했습니다 👍 
리뷰를 소소하게 몇개 남겼는데, 이해안가거나 헷갈리는 부분들은 바로바로 연락주시면 감사할 것 같습니다. 고생많으셨습니다~

2023-09-23 07:48 UTC, sujin9 commented on app/build.gradle.kts
> +    implementation(project(mapOf("path" to ":androidi")))
큰 차이는 없는 것으로 알고 있고, 또한 동일하게 수정해도 변동사항은 없었습니다...
아마 안드로이스 스튜디오에 의해 자동으로 다음과 같이 추가가 된 것 같네요 😂

2023-09-23 07:50 UTC, sujin9 commented on app/src/test/java/woowacourse/shopping/CartActivityTest.kt
> +    fun `Activity를 재생성했을 때, 액티비티 lifecycle을 따르는 필드 객체에 새로운 인스턴스가 주입된다`() {
네 맞습니다! 모듈이 DiActivity의 생명주기에 맞추어 잘 유지되는 지를 확인하려고 작성한 테스트에요.
말씀해주신 것처럼 테스트하려는 내용이 androidi 모듈에 있을 때 의미가 더 맞을 것 같아요!! 👍 :)

2023-09-23 09:45 UTC, sujin9 commented on app/src/main/java/woowacourse/shopping/ui/cart/CartActivity.kt
> +        injectFields()
멘델이 말씀하신 대로, 정확한 순서대로 반드시 호출되어야 하는 경우에는 실수가 발생할 가능성이 다분할 것 같네요! 
우선 DiActivity에서 함수들을 순서대로 호출되도록 구현해서 이 부분을 개선하고자 했어요.

더불어, container에 module 객체들을 생성하여 주입하는 부분은 DiActivity에서 수행하도록 수정함으로써
상속받는 기존 activity의 코드들이 깔끔해지도록 했습니다. :)
다만, 액티비티 객체에서 필드를 주입받는 코드는 여전히, DiActivity의 abstract 메소드를 override 해야 하는 형태입니다.
부모 액티비티(DiActivity)에서 자식 액티비티(Main/CartActivity) 필드 주입을 하는 부분을 
최대한 DiActivity에서 진행할 수 있도록 깔끔하게 개선해보고 싶은데,
부모 액티비티에서 자식 액티비티를 매번 어떻게 알고 instance를 주입할 수 있을지 고민이네요 😢

2023-09-24 08:05 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/shopping/ui/cart/CartActivity.kt
> +        injectFields()
리뷰 반영 잘해주셨네요 하티! 코드가 개선된 것 같아요!! 
하티가 주신 질문에 대해서는, 아래와 같은 답변을 남길게요! 꼭 정답은 아닐 수 있으니 참고만 해주세요 :)
우선, 굳이 부모 클래스가 자식 클래스에 의존할 필요는 없다고 생각합니다. 
CartActivity는 DiActivity를 상속받고 있습니다. 이떄, DiActivity의 onCreate에서 this::class를 호출한다면, 해당 객체는 DiActivity타입이 아니라 여전히 본질적인 객체인 CartActivity타입의 객체입니다. (아래는 실제 출력 예시입니다) 
<img width="741" alt="image" src="https://github.com/woowacourse/android-di/assets/67176829/ec75d740-c447-4091-845c-d5b7adfe7ef1">


그렇다면,  super.onCreate쪽에서 충분히 해당 객체에 대한 필드 주입을 해줄 수 있지 않을까요?? 아래는 기존에 하티가 만들었던 필드 주입 함수의 구성입니다.
<img width="525" alt="image" src="https://github.com/woowacourse/android-di/assets/67176829/2ee20c37-b5c9-46a7-8b96-a3e3e11b4019">

2023-09-24 08:06 UTC, rhthrhrl0 commented on app/build.gradle.kts
> +    implementation(project(mapOf("path" to ":androidi")))
아하, 덕분에 새로운 표현식을 알아가네요~

2023-09-24 08:13 UTC, rhthrhrl0 requested changes
하티 리뷰 반영 고생하셨습니다! 
 저는 이정도면 만족하고 있는데, 하티는 어떠신지 모르겠네요. 하티가 질문 남긴 것에 대해서 금방 수정 가능한 리뷰 하나(+ 1개 더... 총 두 개입니다.)만 더 남겼습니다. 다음 리뷰 요청 때 머지하도록 하겠습니다 :)

2023-09-24 08:15 UTC, rhthrhrl0 commented
> 하티 리뷰 반영 고생하셨습니다! 저는 이정도면 만족하고 있는데, 하티는 어떠신지 모르겠네요. 하티가 질문 남긴 것에 대해서 금방 수정 가능한 리뷰 하나만 더 남겼습니다. 다음 리뷰 요청 때 머지하도록 하겠습니다 :)

사실, 테스트 코드가 살짝 부족한 느낌은 들고 있습니다. 테스트 코드를 더 작성해보셔도 되고, 스텝5 힐트 적용에 도전해보셔도 좋을 것 같습니다. 좀 더 도전해보고 싶은 일에 따라서, 리뷰요청 보내주시면 좋을 것 같습니다.

2023-09-24 08:18 UTC, rhthrhrl0 reviewed
해당 리뷰는 저번에 같이 드렸어야 했는데, 제가 빼먹었었네요. 하지만, 이미 해보셔서 어렵지 않을 것 같습니다.

2023-09-24 08:18 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/shopping/application/ShoppingApplication.kt
> +class ShoppingApplication : DiApplication() {
이 부분도 DiActivity처럼 부모 onCreate쪽에서 해결할 수 있을 것 같네요!

2023-09-24 08:20 UTC, rhthrhrl0 reviewed
해당 리뷰는 저번에 같이 드렸어야 했는데, 제가 빼먹었었네요. 하지만, 이미 해보셔서 어렵지 않을 것 같습니다.

2023-09-24 08:20 UTC, rhthrhrl0 commented on app/src/main/java/woowacourse/shopping/application/ShoppingApplication.kt
> +        injector.addModuleInstances(ApplicationModule(this@ShoppingApplication))
이 부분도 DiActivity처럼 부모 onCreate쪽에서 해결할 수 있을 것 같네요!

2023-09-25 06:06 UTC, sujin9 commented on app/src/main/java/woowacourse/shopping/ui/cart/CartActivity.kt
> +        injectFields()
오,,, DiActivity에서 this::class를 했을 때 Main/CartActivity가 찍힐 줄은 전혀 생각을 못했어요!!
덕분에 코드가 많이 깔끔해질 것 같아요!
알려주셔서 감사합니다 😆 👍

2023-09-25 08:38 UTC, sujin9 commented
> 사실, 테스트 코드가 살짝 부족한 느낌은 들고 있습니다. 테스트 코드를 더 작성해보셔도 되고, 스텝5 힐트 적용에 도전해보셔도 좋을 것 같습니다. 좀 더 도전해보고 싶은 일에 따라서, 리뷰요청 보내주시면 좋을 것 같습니다.

테스트 코드를 더 추가하고 싶어서 살펴보았는데요,,,
제 코드에 제가 묻혀버린건지(?) 어떤 시나리오가 부족한지가 눈에 잘 안 들어오네요 😢😢

2023-09-25 08:39 UTC, sujin9 commented on app/src/main/java/woowacourse/shopping/application/ShoppingApplication.kt
> +        injector.addModuleInstances(ApplicationModule(this@ShoppingApplication))
네 동일한 방식으로 반영했습니다! 👍 
`ShoppingApplication`이 굉장히 깔끔해진 것 같네요 😄

2023-09-25 08:49 UTC, rhthrhrl0 approved these changes
안녕하세요 하티~ 반영해주신 내용 잘 확인했습니다 👍 
미션 내내 하티랑 얘기를 주고 받아서 재밌었습니다 :)
이번 자동 DI 만들기 정말 고생많으셨어요!

2023-09-25 08:53 UTC, rhthrhrl0 commented
> > 사실, 테스트 코드가 살짝 부족한 느낌은 들고 있습니다. 테스트 코드를 더 작성해보셔도 되고, 스텝5 힐트 적용에 도전해보셔도 좋을 것 같습니다. 좀 더 도전해보고 싶은 일에 따라서, 리뷰요청 보내주시면 좋을 것 같습니다.

아 제가 InjectorTest 쪽을 자세히 못 본 것 같습니다. 테스트 코드 충분했네요 하티... 죄송합니다. 정말 고생많으셨어요 :)

2023-09-25 08:56 UTC, merged