[아크] 1단계 자동 DI 미션 제출합니다.
woowacourse/android-di pull request #7
Opened 2023-09-03 17:05 UTC by re4rk

## 안녕하세요!!
코비 안녕하세요! 이번미션 동안 잘부탁드려요!

## 구현 기능 사항
- 이번 DI를 진행하면서 먼저 공부를 진행했습니다! https://github.com/woowacourse/android-di/commit/2dc7fe709625828deebbd201610c10c79a5f87d0
- 우선 저의 DI 핵심 기능은 계층 분리라고 할 수 있습니다!
- Di 패키지에는 DiContainer를 상속하는 `ApiModule`, `DiActivityModule`들로 계층 별로 구성되어있으며 계층마다 주입하고 라이프 사이클을 따라갈 수 있게 설계하였습니다.
- 각 모듈들은 DiContainer를 상속하고 있으며 DiContainer는 부모 DiContainer를 가지고 있으며 자신의 의존성에서 없으면 부모 DI Container에서 탐색하게 만들었으며 최상위 부모까지 찾아도 없으면 null을 반환하게 만들었습니다!
- 구조는 프로퍼티의 getter와 클래스 method를 정의하게 된다면 자동으로 인식하여 의존성이 주입되게 됩니다.
- 마지막으로 의존성을 부여하여 새로운 객체를 만들기 위해서는 `createInstance()`를 호출하면 됩니다.

## 특이사항
- 선택 요구사항을 모두 반영하고 싶었지만 도메인과 리포지터리는 아직 로직글 가지고 있지 않기 때문에 테스트 코드를 추가하지 않았습니다.
- 추가로 Robolectric의 경우에는 모든 경우의 테스트를 추가하고 싶었지만 리사이클러 뷰안의 아이템을 코드로 가져오는 것에 실패하여 반쪽짜리 테스트 코드를 만들었습니다.

## 요구사항
### 기능 요구 사항
생성자 주입 - 수동
- [x] 테스트하기 어렵다.
- [x] Repository 객체를 교체하기 위해 또다른 객체를 만들어 바꿔줘야 한다. 즉, ViewModel에 직접적인 변경사항이 발생한다.

생성자 주입 - 자동
- [x] ViewModel에서 참조하는 Repository가 정상적으로 주입되지 않는다.
- [x] Repository를 참조하는 다른 객체가 생기면 주입 코드를 매번 만들어줘야 한다.
  - [x] ViewModel에 수동으로 주입되고 있는 의존성들을 자동으로 주입되도록 바꿔본다.
  - [x] 특정 ViewModel에서만이 아닌, 범용적으로 활용될 수 있는 자동 주입 로직을 작성한다. (MainViewModel, CartViewModel 모두 하나의 로직만 참조한다)
  - [x] 100개의 ViewModel이 생긴다고 가정했을 때, 자동 주입 로직 100개가 생기는 것이 아니다. 하나의 자동 주입 로직을 재사용할 수 있어야 한다.
- [x] 장바구니에 접근할 때마다 매번 CartRepository 인스턴스를 새로 만들고 있다.
  - [x] 여러 번 인스턴스화할 필요 없는 객체는 최초 한 번만 인스턴스화한다. (이 단계에서는 너무 깊게 생각하지 말고 싱글 오브젝트로 구현해도 된다.)
 
### 선택 요구 사항
- [x] TDD로 DI 구현
- [x] Robolectric으로 기능 테스트
- [x] ViewModel 테스트
- [ ] 모든 도메인 로직, Repository 단위 테스트

### 프로그래밍 요구 사항
- [x] 사전에 주어진 테스트 코드가 모두 성공해야 한다.
- [x] Annotation은 이 단계에서 활용하지 않는다.

2023-09-04 05:57 UTC, rhkrwngud445 requested changes
안녕하세요 아크! 
TDD로 구현하여서 꼼꼼한 테스트가 인상적이었습니다👍
보면서 궁금한 점 위주로 남겼습니다! 그 외에 자잘한 리뷰 남겼는데, 확인 후 반영 부탁드릴게요!

2023-09-04 05:57 UTC, rhkrwngud445 commented on app/src/main/java/woowacourse/shopping/di/DiContainer.kt
> +    }
꼼꼼한 처리네요👍
궁금한 점이 있어요! 생성자 외에 Method 리턴 값이나 Getter에서 꺼내오는 상황을 들었는데, 어떤 시나리오가 있을지 예상이 잘 안됩니다!

2023-09-04 05:57 UTC, rhkrwngud445 commented on domain/src/test/java/woowacourse/shopping/study/DiTest.kt
> +}
학습을 위한 코드일까요~?!

2023-09-04 05:57 UTC, rhkrwngud445 commented on app/src/main/java/woowacourse/shopping/di/ApiModule.kt
> +class ApiModule : DiContainer() {
ApiModule이면 Api 관련 역할을 할 것 같은데, 레포지토리 생성을 하고 있어요!
아크가 생각하시는 ApiModule의 역할은 무엇일까요?!

2023-09-04 05:57 UTC, rhkrwngud445 commented on app/src/main/java/woowacourse/shopping/data/CartSampleRepository.kt
>      private val cartProducts: MutableList<Product> = mutableListOf()
이 부분도 테스트하기 어려운 구조인 것 같아요!

2023-09-05 05:30 UTC, re4rk commented on domain/src/test/java/woowacourse/shopping/study/DiTest.kt
> +}
넵! 처음 사용하는 구조이기 때문에 이를 학습하고 기록하는 용도로 TDD 구현전에 미리 설계해보았습니다!

2023-09-05 05:33 UTC, re4rk commented on app/src/main/java/woowacourse/shopping/di/DiContainer.kt
> +    }
제 DI는 HashMap을 쓰지 않는 대신에 Module이라는 객체들을 통해서 객체들을 주입하기때문에 해당 get함수를 활용해 3가지의 경우로 의존성에 필요한 객체들을 가져오게 됩니다!

1. module 내의 객체를 반환하는 메소드가 있는지 확인
2. module 내의 프로퍼티 중에서 getter가 객체를 반환하는 것이 있는지 확인
3. 모두 실패하면 부모 모듈에서 탐색 시도
이렇게 진행하게 되었습니다!

2023-09-05 05:33 UTC, re4rk commented on app/src/main/java/woowacourse/shopping/data/ProductSampleRepository.kt
> +        )
반영했습니다!

2023-09-05 05:34 UTC, re4rk commented on app/src/main/java/woowacourse/shopping/data/CartSampleRepository.kt
>      private val cartProducts: MutableList<Product> = mutableListOf()
반영했습니다!

2023-09-05 05:34 UTC, re4rk commented on app/src/main/java/woowacourse/shopping/di/ApiModule.kt
> +class ApiModule : DiContainer() {
통일상있게 `DIAppicationModule`와 `DIActivityModule` 으로 변경했습니다!

2023-09-05 05:36 UTC, re4rk commented on app/src/main/java/woowacourse/shopping/AppApplication.kt
> +class AppApplication : DiApplication()
해당 질문에 대해서 잘 이해하지 못하여 조금 더 정확히 설명해주실 수 있을까요?🥲

2023-09-05 13:21 UTC, rhkrwngud445 commented on app/src/main/java/woowacourse/shopping/AppApplication.kt
> +class AppApplication : DiApplication()
상속측면에서 AppApplication이 DiApplication외에 다른 역할이 생길 가능성도 있는데, 상속은 하나의 구현체만 상속 가능하니 AppApplication이 다른 기능이 요구되었을 때 아크는 어떻게 대응할지 궁금했습니다!

2023-09-05 13:29 UTC, rhkrwngud445 approved these changes
추가적인 보완까지 해주셨네요👍
질문주신 부분 코멘트 드렸습니다!
그 외에 잘 반영되어서 찬성할게요~!

2023-09-05 13:36 UTC, merged