[써니] 4단계 자동 DI 미션 제출합니다
woowacourse/android-di pull request #75
Opened 2023-09-19 09:00 UTC by inseonyun

안녕하세요 우기..

2023-09-20 10:08 UTC, boogi-woogi requested changes
써니 4단계 구현하느라 너무 고생하셨습니다~~ 써니가 걱정할만큼 코드 보는 것이 어렵지 않았어요 ㅎㅎ
제가 제대로 이해하지 못한 부분이 있거나 제가 남긴 코멘트에 대해서 궁금한 점이 있다면 언제든지 말씀해주세요~

2023-09-20 10:08 UTC, boogi-woogi commented on di/src/main/java/woowacourse/shopping/di/Module.kt
> +        return instance
제가 이해한 것이 맞다면 모듈이라는 곳에서 의존성 주입에 필요한 객체들을 생성하는 방법을 정의할 수도 있고 의존성을 직접 주입하는 역할도 하는듯 합니다. 역할을 분리해볼 수는 없을까요?

2023-09-20 10:54 UTC, inseonyun commented on di/src/test/java/woowacourse/shopping/di/ModuleTest.kt
> +)
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ
수정하면서 이건 안 고쳤네요 촤핫 : )

2023-09-24 07:39 UTC, inseonyun commented on app/src/main/java/woowacourse/shopping/di/SAnnotation.kt
> +annotation class InMemory
식별은 Qualifier를 갖고 있는지 먼저 확인하고, 둘째로 가지고 있는 Qualifier가 제공하는 provide 함수의 Qualifier가 일치하는지 확인하여 주입하고 있습니다 !
이렇게 하면 Class를 갖게 했을 때 주입하고자 하는 Class를 Import 하여 간접적으로 알게되는 문제, String으로 인해 휴먼 에러가 발생할 수 있는 문제가 해결 가능합니다!

2023-09-26 05:27 UTC, boogi-woogi approved these changes
써니! 고생하셨습니다~ 지금 써니의 코드로 보았을 때 안드로이드 의존성이 있는 di 관련 파일들을 모듈로 분리해도 무방할 것 같다는 생각이 드네요ㅎㅎ

추후에 이 라이브러리를 사용하게 될 날이 있다면 한 번 생각해보셔도 좋을듯 합니다~ di 라이브러리 만들기 미션을 진행하는동안 항상 좋은 리뷰 남겨주셔서 감사합니다~

2023-09-26 05:27 UTC, boogi-woogi commented on di/src/main/java/woowacourse/shopping/di/module/Module.kt
> +            }
사실 instances의 size가 0과 1로 나누어진 것이 어떤 의미인지 enum을 통해서 나타내면 좋을 것 같다라는 생각을 이전부터 했었습니다만 저 또한 좋은 naming이 생각이 나지 않아서 코멘트를 남기지 않았는데 한번 생각해봐도 좋을 것 같아요!

2023-09-26 05:27 UTC, boogi-woogi commented on di/src/main/java/woowacourse/shopping/di/container/InstanceContainer.kt
> +}
분리를 잘해주셨네요~

2023-09-26 05:27 UTC, merged