[올리브] 1단계 자동 DI 미션 제출합니다
woowacourse/android-di pull request #86
Opened 2024-09-04 14:44 UTC by kimhm0728

안녕하세요 서기! 이번 미션 잘 부탁드립니다. 🫒🫒

2024-09-05 02:06 UTC, Namyunsuk commented on app/src/main/java/woowacourse/shopping/ui/util/ViewModelFactory.kt
> +        return if (modelClass.isAssignableFrom(viewModelClass.java)) {
위 코드가 하단의 코드에서 `CartViewModel`과 `CartViewModel::class`를 일치하게 코드를 작성하였는지 확인하는 분기문인가요??
```kotlin
    private val viewModel by viewModels<CartViewModel> { ViewModelFactory(CartViewModel::class, ...) }
```

2024-09-05 04:51 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/di/DIContainer.kt
> +        if (instances.containsKey(classType)) {
네 그래서 Hilt의 `@Named`나 `@Qualifier` 처럼 동일한 타입의 여러 인스턴스의 이름을 지정해서 따로 저장해두려고 했는데요. 이 부분은 step3에서 구현할 내용인 것 같아 일단 이대로 두겠습니다. 다음 단계에 시도해볼게요!

2024-09-05 04:51 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/di/DIContainer.kt
> +    fun <T : Any> get(classType: KClass<T>): T {
"싱글톤으로 생성된 인스턴스를 반환한다"는 의미를 담아서, `singletonInstance()`로 수정했습니다. [f94ca2b](https://github.com/woowacourse/android-di/pull/86/commits/f94ca2ba98b035c25f997ec7553f2541d78d0d3d)

2024-09-05 04:51 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/ui/util/ViewModelFactory.kt
> +        return if (modelClass.isAssignableFrom(viewModelClass.java)) {
네 맞아요~!

2024-09-05 04:52 UTC, kimhm0728 commented
@Namyunsuk  리뷰 반영 사항들은 코멘트로 남겨두었습니다. 아래는 리뷰 반영 외의 리팩터링 내용입니다~!

### 싱글톤 인스턴스와 일반 인스턴스를 분리 [0cb3e84](https://github.com/woowacourse/android-di/pull/86/commits/0cb3e84b8a266ac922c3b241da85edffa040e2d7)
Hilt의 `@Singleton` 어노테이션 처럼, 싱글톤으로 생성되어야 할 인스턴스만 `DIContainer`의 `instances` 프로퍼티에 저장했습니다. 
결론적으로 `DIContainer` 내 인스턴스를 반환하는 함수를 아래처럼 두 가지로 나누었습니다.
- `instance()` 함수: 항상 새로운 인스턴스를 생성 후 반환한다.
- `singletonInstance()` 함수: `instances`에서 이미 생성된 인스턴스를 꺼내 반환한다. 생성된 인스턴스가 없다면 새로운 인스턴스를 생성 후 반환한다.

### 주입할 인스턴스를 Application이 아닌 별도의 클래스에서 관리 [77aa6b6](https://github.com/woowacourse/android-di/pull/86/commits/77aa6b60c08e0b565d448830dce3992aeb2a14e3)
기존에는 `CartRepository`, `ProductRepository` 등을 주입하기 위해 `Application`에서 구현체를 작성했었는데요. 추후 인스턴스가 많아지면 `Application`이 비대해질 것 같아 이를 클래스로 분리했습니다!
- `DIContainer`를 테스트할 경우, `AppDIModule`이 아닌 `TestDIModule` 등을 주입해주기 위해 `DIModule`을 인터페이스로 추상화했습니다.
- `DIModule` 내에 `singletonInstance()` 함수를 따로 만든 이유는, 추후 동일한 타입의 여러 인스턴스가 생성될 경우 인스턴스의 이름을 각각 지정해주려면 `namedInstance()` 등의 함수가 추가될 수 있을 것 같습니다. 즉, 주입할 인스턴스들의 용도를 분리하기 위해 함수로 작성했습니다~!

2024-09-05 07:56 UTC, Namyunsuk commented on app/src/main/java/woowacourse/shopping/di/AppDIModule.kt
> +            Module(ProductRepository::class, DefaultProductRepository()),
type을 명시적으로 넘기지 않고 구현체를 통해 타입을 가져오도록 수정하면
`Module`클래스를 사용하지 않아도 될 것 같다는 생각이 듭니당~

추후의 확장성을 고려하셔서 `Module`을 사용하신 거라면 꼭 반영할 필요는 없을 것 같아요!

2024-09-05 07:56 UTC, Namyunsuk commented on app/src/main/java/woowacourse/shopping/di/DIContainer.kt
> +        return argument
바로 return해줘도 되겠네요..!

2024-09-05 07:56 UTC, Namyunsuk commented on app/src/main/java/woowacourse/shopping/ui/util/ViewModelFactory.kt
> +        return if (modelClass.isAssignableFrom(viewModelClass.java)) {
```kotlin
  private val viewModel by viewModels<CartViewModel>{...}
```
그렇다면 위 코드에서 `CartViewModel`과 `CartViewModel::class`을 같이 넘기기 보다는 타입을 한번만 명시하도록 해주면 위 분기문이 필요없을 것 같슴당

2024-09-05 07:58 UTC, Namyunsuk requested changes
소소하게 남겼습니다~!
화이팅💪

2024-09-05 07:58 UTC, Namyunsuk commented on app/src/main/java/woowacourse/shopping/ui/util/ViewModelFactory.kt
> +        return if (modelClass.isAssignableFrom(viewModelClass.java)) {
```kotlin
  private val viewModel by viewModels<CartViewModel>{...}
```
그렇다면 위 코드에서 `CartViewModel`과 `CartViewModel::class`을 같이 넘기기 보다는 타입을 한번만 명시하도록 해주면 위 분기문이 필요없을 것 같슴당

2024-09-06 05:45 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/ui/util/ViewModelFactory.kt
> +        return if (modelClass.isAssignableFrom(viewModelClass.java)) {
헉스 ㅋㅋ 감사해요 수정했습니다 [0b0a7aa](https://github.com/woowacourse/android-di/pull/86/commits/0b0a7aa57072b852550b84cd9b637b15e7870abb)

2024-09-06 05:45 UTC, kimhm0728 commented on app/src/main/java/woowacourse/shopping/di/DIContainer.kt
> +        return argument
그렇네요 ㄷㄷ 반영했습니다! [ea8cba3](https://github.com/woowacourse/android-di/pull/86/commits/ea8cba3117ac91b8dc1b005bce843352e139c4eb)

2024-09-06 06:14 UTC, Namyunsuk approved these changes
1단계 고생하셨습니다~!
리뷰 진행하면서 저도 정말 많이 배웠어요!
2단계도 화이팅!!!💪

2024-09-06 06:14 UTC, Namyunsuk commented on app/src/main/java/woowacourse/shopping/ui/util/ViewModelFactory.kt
> +        return diContainer.instance(modelClass::class) as T
엄청 간결해졌네요ㄷㄷ👍🏼👍🏼

2024-09-06 06:14 UTC, merged