[해나] 1단계 자동 DI 미션 제출합니다
woowacourse/android-di pull request #95
Opened 2024-09-05 07:48 UTC by hxeyexn

안녕하세요! 해음~
리뷰 잘 부탁드리겠습니다 😊

2024-09-06 02:19 UTC, haeum808 reviewed
고생하셨습니다. 해나!
저는 테스트할 시간이 없어서 못했는데 다 하셨다니 대단합니다!

"궁금한 점:"이 붙은 리뷰들은 답변 부탁드립니다. 잘 몰라서 너무 궁금해요!

2024-09-06 02:19 UTC, haeum808 commented on app/src/main/java/woowacourse/shopping/DependencyInjector.kt
> +    private val instances = mutableMapOf<Class<*>, Any>()
궁금한 점: KClass 대신 Class 사용한 이유가 있나요?

2024-09-06 02:19 UTC, haeum808 commented on app/src/main/java/woowacourse/shopping/DependencyInjector.kt
> +}
궁금한 점: createInstance에서 getInstance를 다시 부르는데 순환 참조 위험이 많진 않을까요?

2024-09-06 02:25 UTC, haeum808 requested changes
리퀘스트 체인지~

2024-09-09 10:17 UTC, hxeyexn commented on app/src/main/java/woowacourse/shopping/ui/cart/CartViewModel.kt
> +        fun factory(): GlobalViewModelFactory =
GlobalViewModelFactory 내부에서 처리하는 방식으로 변경했습니다! [53573a6](https://github.com/woowacourse/android-di/pull/95/commits/53573a6ca87b69f082c01d5de12b40e22e0d031c)

2024-09-09 17:10 UTC, hxeyexn commented on app/src/main/java/woowacourse/shopping/DependencyInjector.kt
> +}
인스턴스를 만들기 위해 getInstance 호출이 계속해서 반복되다가 무한 루프가 발생할 수 있겠군요..! 
순환참조가 발생하지 않도록 아래와 같이 변경했습니다! [2e21fff](https://github.com/woowacourse/android-di/pull/95/commits/2e21fffbbef56f7ffe55701872e80e072825022a)

``` kotlin
private fun <T : Any> KFunction<T>.extractDependencies(): List<Any?> =
    parameters.map { parameter ->
        when (val classifier = parameter.type.classifier) {
            is KClass<*> -> instances[classifier] 
            else -> throw IllegalArgumentException(DEPENDENCY_TYPE_IS_INVALID)
        }
    }
```

2024-09-09 17:17 UTC, hxeyexn commented on app/src/main/java/woowacourse/shopping/DependencyInjector.kt
> +    private val instances = mutableMapOf<Class<*>, Any>()
급하게 코드를 작성하느라 해당 부분은 놓쳤습니다..! 현재 DI 프로그램은 Kotlin 만을 사용하고 있습니다. 따라서 KClass를 활용하는 것이 더 적합하다고 판단해서 KClass를 사용하는 방식으로 수정했습니다~

2024-09-09 17:44 UTC, hxeyexn commented on app/src/main/java/woowacourse/shopping/DependencyInjector.kt
> +object DependencyInjector {
`DependencyInjector`를 `class` 로 변경하고 생성자에서 `context`를 받는 형식으로 변경하면 아래와 같은 코드가 됩니다.

```kotlin
class ShoppingApplication : Application() {
    override fun onCreate() {
        super.onCreate()
        dependencyInjector = DependencyInjector(applicationContext)
        dependencyInjector.initialize()
    }

    companion object {
        lateinit var dependencyInjector: DependencyInjector  // 경고 발생
            private set
    }
}
```
`DependencyInjector`를 외부에서 사용하기 위해 동반 객체 내에 변수를 선언해야하는 데 이때 아래와 같은 경고가 발생합니다 🥹
`정적 필드`에 `Android 컨텍스트 클래스`를 넣으면 메모리 누수가 발생한다고 하네요!

<img width="945" alt="image" src="https://github.com/user-attachments/assets/02131c81-dff3-447a-b35c-55926e95936e">  

<br>
<br>

`DependencyInjector`도 테스트하기 쉽게 하는 방법에 대해서는 좀 더 고민해봐야할 것 같습니다.. 🥲
고민해볼만한 코멘트 남겨주셔서 감사합니다~ 🙇‍♂️

2024-09-09 17:44 UTC, hxeyexn commented on app/src/test/java/woowacourse/shopping/TestFixture.kt
> +object TestFixture {
감사합니다! 😊

2024-09-10 01:09 UTC, merged