[벼리] 1단계 자동 DI 미션 제출합니다
woowacourse/android-di pull request #97
Opened 2024-09-05 08:20 UTC by gaeun5744

오랜만이에요 케이엠!! 이번 미션 잘 부탁드려요!!! 😆😆

### 전달 사항

로직에 대해 간단히 설명드리겠습니다!

RepositoryDI.kt
```
// 자동 DI를 적용하는 Repository를 구분하기 위해 사용
interface RepositoryDI 

class RepositoryBinder { 
// 어떤 interface 객체를 사용할지 구분하는 클래스
    fun provide ~

}
```

RepositoryModule.kt
```
class RepositoryModule private constructor() : DefaultLifecycleObserver {
    override fun onCreate(owner: LifecycleOwner) { 
        // 생명주기에 맞춰 repository 객체를 생성하고 저장
    }

    companion object { 
        fun setLifeCycle(context: Context) 
        // 파라미터로 들어온 context의 생명주기에 맞춰서 객체 scope 범위 지정
}

```

getInjectedViewModelFactory.kt
- 자동으로 의존성을 주입하여 viewModel 객체 생성

---

저같은 경우에는, 객체에 대한 의존성 주입을 한 곳에서가 아니라 역할과 scope에 따라 다양하게 관리하고 싶어서 `RepositoryModule` 이라고 이름 지었습니다

2024-09-05 10:30 UTC, kmkim2689 commented
> 이유는 모르겠지만.. kt 파일이 아닌 다른 txt 파일에 의해 ktlintFormatting이 막히고 있는 상황입니다... 꼭 해결하고 추후에 lint 체크를 하겠습니다ㅠㅠ

지금 프로젝트를 클론하여 lint check를 진행해 보았는데, 저의 컴퓨터 측에서는 txt 파일이 아니라 kt 파일들에서 lint 통과가 되지 않는 상황입니다...! 참고용으로 캡쳐본 남기도록 하겠습니다!
![스크린샷 2024-09-05 19 27 12](https://github.com/user-attachments/assets/b2229fb5-0621-4489-ad19-557b726f5915)

2024-09-05 12:18 UTC, kmkim2689 requested changes
벼리 안녕하세요! 케이엠입니다😃
1단계 미션 진행하시느라 수고 많으셨습니다.
짧은 지식이지만 이번 미션 잘 부탁드리겠습니다ㅎㅎ

리플렉션 활용과 생명주기 관리 등 생각지 못한 곳에서 인사이트를 얻을 수 있었어요.
구현하신 코드 분석하면서 많이 배워갑니다!

구현 잘 해주신 것 같아 특별한 피드백보다는 저의 의견과 궁금증들 위주로 코멘트 남겨보았습니다.
코멘트 중 이해가 되지 않는 부분이 있으시다면 언제든 질문 부탁드리겠습니다!

그럼 이번 미션 화이팅입니다 👍

2024-09-05 12:18 UTC, kmkim2689 commented on app/src/main/java/woowacourse/shopping/ui/injection/RepositoryModule.kt
> +            }
혹시 setLifecycle 함수는 애플리케이션이 실행되는 동안 단 한번만 호출되는 것인가요?
현재로서는 프로덕션 코드(테스트 제외) 기준 애플리케이션 전역 측면으로만 주입을 진행하고 있는 것 같은데, 다른 컴포넌트에서도 호출되는 것인지 궁금해서요!🤔

2024-09-05 12:18 UTC, kmkim2689 commented on app/src/main/java/woowacourse/shopping/ui/injection/RepositoryDI.kt
> +class RepositoryBinder {
싱글톤도 괜찮을 것 같은데, Object로 선언해보는 것은 어떨까요?

2024-09-05 13:16 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/ui/injection/RepositoryModule.kt
> +            .mapNotNull { kFunction ->
아 이부분은 저의 실수입니다ㅠ 
이전 코드에서는 null을 반환하는 로직이 있었는데, 코드를 수정하면서 null을 반환하는 로직이 사라졌네요... 짚어주셔서 감사합니다!!

2024-09-06 05:55 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/ui/injection/RepositoryModule.kt
> +            ?: error("${repository.simpleName} 해당 interface에 대한 객체가 없습니다.")
저는 저장하는 형태를 바꿀려고 했습니다!

```
private lateinit var repositoryMap: Map<String, Map<tag, RepositoryDI>>

fun getRepository(repository: KClass<out RepositoryDI>, type:String = DEFAULT_TAG): RepositoryDI

```

다만... `repositoryMap`의 타입이 너무 복잡해서, 다른 방법을 찾아보고 있습니다! 🥹

2024-09-06 06:36 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/ui/injection/InjectedViewModelFactory.kt
> +            }
이 부분은 3단계에 있는 내용이라서 추후에 반영하겠습니다!!

2024-09-07 14:30 UTC, kmkim2689 commented on app/src/main/java/woowacourse/shopping/ui/injection/RepositoryDI.kt
> +class RepositoryBinder {
벼리 나름의 타당한 근거를 바탕으로 배치하셨다고 하니 답변주신 사항에 납득이 됩니다!
다만 해당 배치에 대해서는 해당 코드를 접할 팀원들에게 충분한 설득이 필요할 것 같다는 생각이 들었어요!

왜냐하면 해당 코드를 처음 접해보았던 저는 Binder 클래스의 사용법에 대해 궁금했다기보다는 '두 객체가 어떤 연관성이 있길래 같이 배치가 된거지?'하는 생각이 들었거든요😂 RepositoryDI가 provide 함수의 반환 타입에 숨겨져 있어 더 그렇게 생각했던 것 같아요.

물론 공식문서에서의 서술은 벼리의 의견처럼 여러 여지로 해석될 수 있을 것 같습니다.
공식문서 상에서 의미적으로(sementically) 연관있는 클래스, 최상위 함수, 프로퍼티끼리 한 파일에 같이 둘 수 있다고 하는데, 저는 `의미적으로 밀접하다`의 의미를 다르게 생각하고 있었을지도 모르겠습니다. 

저는 명백히 동등한 관계이면서 도메인 배치 상 한 파일에 두어도 무관한 클래스들이거나(적어도 파일 상 모든 객체에 객체명이든 상속이든 어떤 형태로든 특정 워딩이 빠짐없이 나타남),
최상위 확장함수(Mapper 같은...)같이 비슷한 맥락에서 사용되는 객체일 때만 같은 파일에 둬야 한다고 생각했었거든요!

이상 그냥 제 의견일 뿐이었고,, '그냥 이렇게 생각하는 사람도 있구나'라고 생각해주시면 감사하겠습니다😅

2024-09-07 14:35 UTC, kmkim2689 commented on app/src/main/java/woowacourse/shopping/ui/injection/InjectedViewModelFactory.kt
> +            }
넵넵 3단계 미션 진행하면서 이야기 나눠보시죠ㅎㅎ

다만 주입의 대상이 ViewModel뿐만 아니라 다른 일반적인 객체가 된다면 그 때는 어떻게 해야할지도 생각을 해봐야 할 것 같아요!

언젠가 Repository 혹은 어떤 이름이 될지 모르는 class에도 의존성을 주입해야 할 때가 오게 될 것 같은데, 그때마다 인터페이스를 만드는 것은 힘들지 않을까 싶어서요 😂

2024-09-07 14:36 UTC, kmkim2689 commented on app/src/main/java/woowacourse/shopping/ui/injection/RepositoryModule.kt
> +            ?: error("${repository.simpleName} 해당 interface에 대한 객체가 없습니다.")
이거는 저도 아직 고민 중인 사항이라 좋은 방법 생기면 같이 공유해보시죠! 👍

2024-09-08 12:57 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/ui/injection/RepositoryDI.kt
> +class RepositoryBinder {
둘의 연관관계가 부족하다는 생각이 들어서, init 블록에 `RepositoryDI`와 `RepositoryBinder`의 연관관계를 추가했습니다! 다만... 의미적으로 밀접하다는 너무 주관적이라 기준을 세우기가 어렵네요😐  좋은 의견 감사합니다!!! 😊

2024-09-08 12:58 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/ui/injection/InjectedViewModelFactory.kt
> +            }
코멘트를 반영해서, 최대한 범용적으로 쓰일 수 있는 `createInjectedInstance` 객체를 만들었습니다! 모듈 자체는 Repository, DataSource 등등 역할을 분리했지만, 객체 주입 자체는 한 곳에서 관리하는 방법밖에 생각이 안나네요...ㅠㅠㅠ

2024-09-08 13:12 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/ui/injection/RepositoryModule.kt
> +        repositoryMap = createRepositoryMap(repositoryBinder)
최대한 에러를 빨리 터뜨려서, 다른 개발자가 빠르게 수정할 수 있도록 코드를 바꿨습니다!

viewModel.kt
```
class MainViewModel(
    val repository ....

): ViewModel(), DIInjection {

    init {
        checkConstructor()
    }

}
```

다만.. `InjectViewModel` 추상 클래스를 만들어 init 로직을 강제할지 말지 고민이 되어서 우선은 인터페이스만 만들어 두었습니다!

2024-09-08 13:15 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/ui/injection/RepositoryModule.kt
> +class RepositoryModule private constructor() : DefaultLifecycleObserver {
네네 맞습니다!! 또한 Repostiory 객체 각각에 대해 컴포넌트 생명주기를 넣어줄까 하다가... 로직이 너무 복잡해져서 우선은 Module에 대해서만 생명주기를 따르도록 했습니다!

2024-09-08 13:16 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/ui/injection/RepositoryDI.kt
> +class RepositoryBinder {
`RepositoryBinder` 객체도 생명주기에 맞추서 생성되고 소멸되도록 두었기 때문에 `object`로 두기는 어렵습니다ㅠ

2024-09-08 13:22 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/ui/injection/RepositoryModule.kt
> +            }
아뇨!! 한 번만 호출될 것을 기대하고 작성한 코드입니다.
다만, 여러번 호출 될 때에 대한 안내가 없어서 이와 관련된 코드를 추가했습니다. 짚어주셔서 감사합니다!

RepositoryModule.kt
```
        fun initLifeCycle(context: Context) {
            require(instance == null) {
                "Module은 한번만 초기화가 가능합니다."
            }
        }
```

2024-09-08 13:34 UTC, gaeun5744 commented
안녕하세요 케이엠! 꼼꼼하게 봐주신 덕분에 여러가지로 수정할 수 있었습니다 😄 
구현에 급급해서 다양한 예외상황을 고려하지 못했었는데, 덕분에 기반을 잡고 갑니다!!

## 수정 사항
### 에러 대응
- 기존 : ViewModel에 대해서만 DI 객체 주입을 
- 개선 : 어떠한 객체든 상관없이, `DIInjection`을 상속받고 있다면 객체 주입 가능
CreateInjectedInstance.kt
```
fun <T : DIInjection> createInjectedInstance(clazz: KClass<T>): T
```
### 런타임 에러
- 기존 : 런타임시 발생할 수 있는 예상치 못한 에러 대응 부족
- 개선 : `require` 과 `init`을 활용하여, 개발자가 로직을 제대로 구현하지 않으면 예외가 발생하도록 함

## 한계점

`DataSourceModule` 등의 모듈이 추가될 때 마다 `createInjectedInstance`와 `checkConstructor` 메서드 내부 `when` 구문에  로직을 추가해야한다는 번거로움이 있었습니다.

리플렉션은 런타임시에만 알 수 있기 때문에, 이에 대한 처리를 강제하기 힘들어서 우선은 이대로 두었습니다.

### ktlint

2024-09-09 04:30 UTC, kmkim2689 commented
벼리 안녕하세요!
제 기준에서 코드를 돌려보았을 때, 아래와 같이 린트를 통과하지 못하는 상황입니다.
참고 부탁드리겠습니다🥲
![image](https://github.com/user-attachments/assets/5ae1e604-72d6-4e33-be99-87e3474f9056)

2024-09-09 06:36 UTC, kmkim2689 approved these changes
벼리 안녕하세요!
이번 1단계 미션 피드백 반영 하시느라 수고 많으셨습니다!

피드백 반영하시느라 고민 많이 하신 것이 느껴지네요!
빠른 2, 3단계 진행을 위하여 이번 단계는 merge하겠습니다😄
논의했던 사항들은 다음 단계에서 같이 고민해보도록 하시죠!

추가적으로 피드백 드리고 싶은 사항이 있어 소소하게 몇 개 남겨보았습니다.
다음 단계 진행하시면서 필요하신 사항 반영해주시면 될 것 같습니다.
2, 3단계도 응원하겠습니다⭐🌟

2024-09-09 06:36 UTC, kmkim2689 commented on app/src/test/java/woowacourse/shopping/MainActivityTest.kt
> +@Config(application = TestApplication::class)
혹시 화면이 추가되면 별도로 다른 애플리케이션을 마련하실 계획이신지 궁금합니다🤔
그것이 아니라면 테스트 클래스가 추가될 때마다 해당 `@Config` 어노테이션을 사용해야 할텐데, 한큐에 진행할 더 좋은 방법이 있어 공유드립니다!
[참고 링크](https://charlezz.com/?p=44348)

2024-09-09 06:36 UTC, kmkim2689 commented on app/src/main/java/woowacourse/shopping/ui/injection/repository/RepositoryDI.kt
> +    }
예외 처리의 권위자답게 초기 예외를 잘 처리해주셨군요!

2024-09-09 06:36 UTC, merged

2024-09-09 06:54 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/ui/injection/repository/RepositoryModule.kt
> +        fun getInstanceOrNull(): RepositoryModule? = instance
해당 코드에 대한 착안은, 코틀린 기본 function에서 가져왔습니다!

예를 들어서 int로 변환하는 로직은 toInt()와 toIntOrNull()이 있습니다. 이렇게 두가지로 나눈 이유는, 해당 로직을 사용하는 개발자에게 예외 처리에 대한 선택권을 주기 위해서 입니다.

지금은 테스트코드에서만 쓰이지만, 추후에는 프로덕션 코드에서도 필요한 로직 중 하나라 생각하기 때문에 추가했습니다!

2024-09-09 06:56 UTC, gaeun5744 commented on app/src/test/java/woowacourse/shopping/MainActivityTest.kt
> +@Config(application = TestApplication::class)
새로운 방법이 있었네요! 덕분에 참고합니다!

2024-09-09 06:58 UTC, gaeun5744 commented on app/src/main/java/woowacourse/shopping/ui/injection/DIInjection.kt
> +}
좋은 글 공짜로 읽고 갑니다 😊